# Python Data Science Handbook

## 2. Introduction to NumPy

In [1]:
import numpy
numpy.__version__

'1.21.5'

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

### Understanding Data Types in Python

In [4]:
result = 0

for i in range(100):
    result += i

In [5]:
result

4950

In [6]:
x = 4
x = 'four'

### A Python List Is More Than Just a List

In [7]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
type(L[0])

int

In [12]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [14]:
L3 = [True, '2', 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

### Fixed-Type Arrays in Python

In [15]:
import array

L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating Arrays from Python Lists

In [16]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [18]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [19]:
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [21]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

In [22]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [25]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
np.random.random((3, 3))

array([[0.28903233, 0.40638302, 0.82871214],
       [0.24042723, 0.15292086, 0.00835182],
       [0.24256513, 0.75542746, 0.11880028]])

In [28]:
np.random.normal(0, 1, (3, 3))

array([[ 0.02756398, -0.58505999, -0.01349804],
       [ 0.72621408, -0.49848792, -0.25243362],
       [-1.40692259, -0.62445091,  0.16418037]])

In [29]:
np.random.randint(0, 10, (3, 3))

array([[9, 9, 6],
       [7, 6, 1],
       [3, 2, 1]])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.empty(3)

array([1., 1., 1.])

### NumPy Standard Data Types

In [32]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [33]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [40]:
np.zeros(10, dtype='uint64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint64)

### NumPy Array Attributes

In [51]:
rng = np.random.default_rng(seed=1701)

x1 = rng.integers(10, size=6)
x2 = rng.integers(10, size=(3, 4))
x3 = rng.integers(10, size=(3, 4, 5))

print(x1, '\n', '\n')
print(x2, '\n', '\n')
print(x3)

[9 4 0 3 8 6] 
 

[[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]] 
 

[[[4 3 5 5 0]
  [8 3 5 2 2]
  [1 8 8 5 3]
  [0 0 8 5 8]]

 [[5 1 6 2 3]
  [1 2 5 6 2]
  [5 2 7 9 3]
  [5 6 0 2 0]]

 [[2 9 4 3 9]
  [9 2 2 4 0]
  [0 3 0 0 2]
  [3 2 7 4 7]]]


In [46]:
print('x3 ndim: ', x3.ndim)
print('x3 shape:', x3.shape)
print('x3 size: ', x3.size)
print('dtype:   ', x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


### Array Indexing: Accessing Single Elements

In [53]:
x1

array([9, 4, 0, 3, 8, 6], dtype=int64)

In [54]:
x1[0]

9

In [55]:
x1[-1]

6

In [56]:
x1[-2]

8

In [57]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]], dtype=int64)

In [58]:
x2[0, 0]

3

In [59]:
x2[2, 0]

0

In [60]:
x2[2, -1]

9

In [61]:
x2[0, 0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [62]:
x1[0] = 3.14159
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)

### Array Slicing: Accessing Subarrays. One-Dimensional Subarrays

In [63]:
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)

In [64]:
x1[:3]

array([3, 4, 0], dtype=int64)

In [65]:
x1[3:]

array([3, 8, 6], dtype=int64)

In [67]:
x1[1:4]

array([4, 0, 3], dtype=int64)

In [68]:
x1[1::2]

array([4, 3, 6], dtype=int64)

In [69]:
x1[::-1]

array([6, 8, 3, 0, 4, 3], dtype=int64)

In [70]:
x1[4::-2]

array([8, 0, 3], dtype=int64)

### Multidimensional Subarrays

In [71]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [72]:
x2[:2, :3]

array([[12,  1,  3],
       [ 4,  0,  2]], dtype=int64)

In [73]:
x2[:3, ::2]

array([[12,  3],
       [ 4,  2],
       [ 0,  6]], dtype=int64)

In [74]:
x2[::-1, ::-1]

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]], dtype=int64)

In [77]:
x2[:, 0]

array([12,  4,  0], dtype=int64)

In [78]:
x2[0, :]

array([12,  1,  3,  7], dtype=int64)

In [79]:
x2[0]

array([12,  1,  3,  7], dtype=int64)