# Python Data Science Handbook

## 3. Data Manipulation with Pandas

In [1]:
import pandas
pandas.__version__

'1.4.4'

In [3]:
import pandas as pd

In [4]:
pd?

Type:        module
String form: <module 'pandas' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pandas\\__init__.py'>
File:        c:\programdata\anaconda3\lib\site-packages\pandas\__init__.py
Docstring:  
pandas - a powerful data analysis and manipulation library for Python

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be ins

### Introducing Pandas Objects

In [5]:
import numpy as np
import pandas as pd

### The Pandas Series Object

In [6]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [7]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [8]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
data[1]

0.5

In [10]:
data[1:3]

1    0.50
2    0.75
dtype: float64

### Series as Generalized NumPy Array

In [11]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index = ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [12]:
data['b']

0.5

In [13]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index = [2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [14]:
data[5]

0.5

### Series as Specialized Dictionary

In [15]:
population_dict = {'California': 39538223, 'Texas': 29145505,
                   'Florida': 21538187, 'New York': 20201249,
                   'Pennsylvania': 13002700}
population = pd.Series(population_dict)

population

California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700
dtype: int64

In [16]:
population['California']

39538223

In [18]:
population['California':'Florida']

California    39538223
Texas         29145505
Florida       21538187
dtype: int64

### Constructing Series Objects

In [20]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [22]:
pd.Series(5, index = [100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [23]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [24]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[1, 2])

1    b
2    a
dtype: object

### DataFrame as Generalized NumPy Array

In [25]:
area_dict = {'California': 423967, 'Texas': 695662, 'Florida': 170312,
             'New York': 141297, 'Pennsylvania': 119280}

area = pd.Series(area_dict)

area

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
dtype: int64

In [27]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California      39538223  423967
Texas           29145505  695662
Florida         21538187  170312
New York        20201249  141297
Pennsylvania    13002700  119280

In [28]:
states.index

Index(['California', 'Texas', 'Florida', 'New York', 'Pennsylvania'], dtype='object')

In [29]:
states.columns

Index(['population', 'area'], dtype='object')

### DataFrame as Specialized Dictionary

In [30]:
states['area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

### Constructing DataFrame Objects

In [31]:
pd.DataFrame(population, columns = ['population'])

population
California      39538223
Texas           29145505
Florida         21538187
New York        20201249
Pennsylvania    13002700

In [32]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]

pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [33]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [34]:
pd.DataFrame({'population': population,
              'area': area})

population    area
California      39538223  423967
Texas           29145505  695662
Florida         21538187  170312
New York        20201249  141297
Pennsylvania    13002700  119280

In [35]:
pd.DataFrame(np.random.rand(3, 2),
             columns = ['foo', 'bar'],
             index = ['a', 'b', 'c'])

foo       bar
a  0.385912  0.185063
b  0.620482  0.206212
c  0.550815  0.447333

In [37]:
A = np.zeros(3, dtype = [('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [38]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

### The Pandas Index Object

In [39]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

### Index as Immutable Array

In [41]:
ind[1]

3

In [42]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [43]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


### Index as Ordered Set

In [45]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [46]:
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

In [47]:
indA.union(indB)

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [48]:
indA.symmetric_difference(indB)

Int64Index([1, 2, 9, 11], dtype='int64')

### Series as Dictionary

In [1]:
import pandas as pd

In [4]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index = ['a', 'b', 'c', 'd'])

data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [5]:
data['b']

0.5

In [6]:
'a' in data

True

In [7]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [8]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [9]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

### Series as One-Dimensional Array

In [11]:
# Slicicng by explicit index
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [12]:
# Slicing by implicit integer index
data[0:2]

a    0.25
b    0.50
dtype: float64

In [13]:
# Masking
data[(data > 0.3) & (data <0.8)]

b    0.50
c    0.75
dtype: float64

In [14]:
# Fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

### Indexers: <code>loc</code> and <code>iloc</code>

In [15]:
data[1]

0.5

In [16]:
data[1:3]

b    0.50
c    0.75
dtype: float64

In [17]:
data = pd.Series(['a', 'b', 'c'], index = [1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [18]:
# Explicit index when indexing
data[1]

'a'

In [21]:
data[3]

'b'

In [19]:
# Implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

In [22]:
data.loc[1]

'a'

In [23]:
data.loc[1:3]

1    a
3    b
dtype: object

In [24]:
data.iloc[1]

'b'

In [25]:
data.iloc[1:3]

3    b
5    c
dtype: object

### DataFrame as Dictionary

In [26]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'Florida': 170312, 'New York': 141297,
                  'Pennsylvania': 119280})

pop = pd.Series({'California': 39538223, 'Texas': 29145505,
                 'Florida': 21538187, 'New York': 20201249, 
                 'Pennsylvania': 13002700})

data = pd.DataFrame({'area': area, 'pop': pop})

data

area       pop
California    423967  39538223
Texas         695662  29145505
Florida       170312  21538187
New York      141297  20201249
Pennsylvania  119280  13002700

In [27]:
data['area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [28]:
data.area

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [29]:
data.pop is data['pop']

False

In [30]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California    423967  39538223   93.257784
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

### DataFrame as Two-Dimensional Array

In [31]:
data.values

array([[4.23967000e+05, 3.95382230e+07, 9.32577842e+01],
       [6.95662000e+05, 2.91455050e+07, 4.18960717e+01],
       [1.70312000e+05, 2.15381870e+07, 1.26463121e+02],
       [1.41297000e+05, 2.02012490e+07, 1.42970120e+02],
       [1.19280000e+05, 1.30027000e+07, 1.09009893e+02]])

In [32]:
data.T

California         Texas       Florida      New York  Pennsylvania
area     4.239670e+05  6.956620e+05  1.703120e+05  1.412970e+05  1.192800e+05
pop      3.953822e+07  2.914550e+07  2.153819e+07  2.020125e+07  1.300270e+07
density  9.325778e+01  4.189607e+01  1.264631e+02  1.429701e+02  1.090099e+02

In [33]:
data.values[0]

array([4.23967000e+05, 3.95382230e+07, 9.32577842e+01])

In [34]:
data['area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
Name: area, dtype: int64

In [35]:
data.iloc[:3, :2]

area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

In [36]:
data.loc[:'Florida', :'pop']

area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

In [37]:
data.loc[data.density > 120, ['pop', 'density']]

pop     density
Florida   21538187  126.463121
New York  20201249  142.970120

In [40]:
data.iloc[0, 2] = 90
data

area       pop     density
California    423967  39538223   90.000000
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvania  119280  13002700  109.009893

### Additional Indexing Conventions

In [41]:
data['Florida':'New York']

area       pop     density
Florida   170312  21538187  126.463121
New York  141297  20201249  142.970120

In [42]:
data[1:3]

area       pop     density
Texas    695662  29145505   41.896072
Florida  170312  21538187  126.463121

In [43]:
data[data.density > 120]

area       pop     density
Florida   170312  21538187  126.463121
New York  141297  20201249  142.970120

### Ufuncs: Index Preservation

In [1]:
import pandas as pd
import numpy as np

In [45]:
rng = np.random.default_rng(42)
ser = pd.Series(rng.integers(0, 10, 4))
ser

0    0
1    7
2    6
3    4
dtype: int64

In [47]:
df = pd.DataFrame(rng.integers(0, 10, (3, 4)),
                  columns = ['A', 'B', 'C', 'D'])
df

A  B  C  D
0  4  8  0  6
1  2  0  5  9
2  7  7  7  7

In [48]:
np.exp(ser)

0       1.000000
1    1096.633158
2     403.428793
3      54.598150
dtype: float64

In [49]:
np.sin(df * np.pi / 4)

A             B         C         D
0  1.224647e-16 -2.449294e-16  0.000000 -1.000000
1  1.000000e+00  0.000000e+00 -0.707107  0.707107
2 -7.071068e-01 -7.071068e-01 -0.707107 -0.707107

### Index Alignment in Series

In [50]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name = 'area')

population = pd.Series({'California': 39538223, 'Texas': 29145505,
                        'Florida': 21538187}, name = 'population')

In [51]:
population / area

Alaska              NaN
California    93.257784
Florida             NaN
Texas         41.896072
dtype: float64

In [52]:
area.index.union(population.index)

Index(['Alaska', 'California', 'Florida', 'Texas'], dtype='object')

In [53]:
A = pd.Series([2, 4, 6], index = [0, 1, 2])
B = pd.Series([1, 3, 5], index = [1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [54]:
A.add(B, fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### Index Alignment in DataFrames

In [56]:
A = pd.DataFrame(rng.integers(0, 20, (2, 2)),
                 columns = ['a', 'b'])
A

a  b
0  10  2
1  16  9

In [57]:
B = pd.DataFrame(rng.integers(0, 10, (3, 3)),
                 columns = ['b', 'a', 'c'])
B

b  a  c
0  5  3  1
1  9  7  6
2  4  8  5

In [58]:
A + B

a     b   c
0  13.0   7.0 NaN
1  23.0  18.0 NaN
2   NaN   NaN NaN

In [60]:
A.add(B, fill_value = A.values.mean())

a      b      c
0  13.00   7.00  10.25
1  23.00  18.00  15.25
2  17.25  13.25  14.25

### Ufuncs: Operations Between DataFrames and Series

In [61]:
A = rng.integers(10, size = (3, 4))
A

array([[4, 4, 2, 0],
       [5, 8, 0, 8],
       [8, 2, 6, 1]], dtype=int64)

In [62]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 1,  4, -2,  8],
       [ 4, -2,  4,  1]], dtype=int64)

In [63]:
df = pd.DataFrame(A, columns = ['Q', 'R', 'S', 'T'])
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  1  4 -2  8
2  4 -2  4  1

In [64]:
df.subtract(df['R'], axis = 0)

Q  R  S  T
0  0  0 -2 -4
1 -3  0 -8  0
2  6  0  4 -1

In [65]:
halfrow = df.iloc[0, ::2]
halfrow

Q    4
S    2
Name: 0, dtype: int64

In [66]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  1.0 NaN -2.0 NaN
2  4.0 NaN  4.0 NaN

### Missing Data in Pandas

In [1]:
import numpy as np
import pandas as pd

### <code>None</code> as a Sentinel Value

In [2]:
vals1 = np.array([1, None, 2, 3])
vals1

array([1, None, 2, 3], dtype=object)

In [3]:
%timeit np.arange(1E6, dtype = int).sum()

1.94 ms ± 30.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%timeit np.arange(1E6, dtype = object).sum()

53.2 ms ± 538 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
# Leads to error:
# vals1.sum()

### <code>NaN</code>: Missing Numerical Data

In [7]:
vals2 = np.array([1, np.nan, 3, 4])
vals2

array([ 1., nan,  3.,  4.])

In [8]:
1 + np.nan

nan

In [9]:
0 * np.nan

nan

In [10]:
10 * np.nan

nan

In [11]:
vals2.sum(), vals2.min(), vals2.max()

(nan, nan, nan)

In [12]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(8.0, 1.0, 4.0)

### <code>NaN</code> and <code>None</code> in Pandas

In [13]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [14]:
pd.Series([1, 2, None])

0    1.0
1    2.0
2    NaN
dtype: float64

In [15]:
pd.Series([1, 2, np.nan])

0    1.0
1    2.0
2    NaN
dtype: float64

In [16]:
x = pd.Series(range(2), dtype = int)
x

0    0
1    1
dtype: int32

In [17]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

In [22]:
x2 = pd.Series(['a', 'b'], dtype = object)
x2

0    a
1    b
dtype: object

In [24]:
x2[0] = None
x2

0    None
1       b
dtype: object

In [25]:
x3 = pd.Series([1.1, 1.2], dtype = float)
x3

0    1.1
1    1.2
dtype: float64

In [26]:
x3[0] = None
x3

0    NaN
1    1.2
dtype: float64

In [27]:
x4 = pd.Series([0, 0, 1, 1], dtype = bool)
x4

0    False
1    False
2     True
3     True
dtype: bool

In [28]:
x4[0] = None
x4

0      NaN
1    False
2     True
3     True
dtype: object

### Pandas Nullable Dtypes

In [30]:
pd.Series([1, np.nan, 2, None, pd.NA], dtype = 'Int32')

0       1
1    <NA>
2       2
3    <NA>
4    <NA>
dtype: Int32

In [35]:
pd.Series([1, np.nan, 2, None, pd.NA])

0       1
1     NaN
2       2
3    None
4    <NA>
dtype: object

### Detecting Null Values

In [4]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [3]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [5]:
data[data.notnull()]

0        1
2    hello
dtype: object

### Dropping Null Values

In [6]:
data.dropna()

0        1
2    hello
dtype: object

In [9]:
df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [10]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [11]:
df.dropna(axis=1)

2
0  2
1  5
2  6

In [12]:
df.dropna(axis = 'columns')

2
0  2
1  5
2  6

In [13]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [14]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [15]:
df.dropna(axis = 'columns', how = 'all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [16]:
df.dropna(axis = 'rows', thresh = 3)

0    1  2   3
1  2.0  3.0  5 NaN

### Filling Null Values

In [17]:
data = pd.Series([1, np.nan, 2, None, 3], index = list('abcde'),
                 dtype = 'Int32')
data

a       1
b    <NA>
c       2
d    <NA>
e       3
dtype: Int32

In [18]:
data.fillna(0)

a    1
b    0
c    2
d    0
e    3
dtype: Int32

In [19]:
# Forward fill
data.fillna(method = 'ffill')

a    1
b    1
c    2
d    2
e    3
dtype: Int32

In [20]:
# Back fill
data.fillna(method = 'bfill')

a    1
b    2
c    2
d    3
e    3
dtype: Int32

In [21]:
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [22]:
df.fillna(method = 'ffill', axis = 1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

### Hierarchical Indexing

In [2]:
import pandas as pd
import numpy as np

### A Multiply Indexed Series
### The Bad Way

In [3]:
index = [('California', 2010), ('California', 2020),
         ('New York', 2010), ('New York', 2020),
         ('Texas', 2010), ('Texas', 2020)]

populations = [37253956, 39538223,
               19378102, 20201249,
               25145561, 29145505]

pop = pd.Series(populations, index = index)
pop

(California, 2010)    37253956
(California, 2020)    39538223
(New York, 2010)      19378102
(New York, 2020)      20201249
(Texas, 2010)         25145561
(Texas, 2020)         29145505
dtype: int64

In [4]:
pop[('California', 2020):('Texas', 2010)]

(California, 2020)    39538223
(New York, 2010)      19378102
(New York, 2020)      20201249
(Texas, 2010)         25145561
dtype: int64

In [5]:
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

### The Better Way: The Pandas <code>MultiIndex</code>

In [6]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2010),
            ('California', 2020),
            (  'New York', 2010),
            (  'New York', 2020),
            (     'Texas', 2010),
            (     'Texas', 2020)],
           )

In [7]:
pop = pop.reindex(index)
pop

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [8]:
pop[:, 2020]

California    39538223
New York      20201249
Texas         29145505
dtype: int64

### <code>MultiIndex</code> as Extra Dimension

In [9]:
pop

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [10]:
pop_df = pop.unstack()
pop_df

2010      2020
California  37253956  39538223
New York    19378102  20201249
Texas       25145561  29145505

In [11]:
pop_df.stack()

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [12]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9284094, 8898092, 
                                   4318033, 4181528, 
                                   6879014, 7432474]})

pop_df

total  under18
California 2010  37253956  9284094
           2020  39538223  8898092
New York   2010  19378102  4318033
           2020  20201249  4181528
Texas      2010  25145561  6879014
           2020  29145505  7432474

In [13]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()

2010      2020
California  0.249211  0.225050
New York    0.222831  0.206994
Texas       0.273568  0.255013

### Methods of <code>MultiIndex</code> Creation

In [14]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index = [['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns = ['data1', 'data2'])
df

data1     data2
a 1  0.055099  0.955389
  2  0.351874  0.555276
b 1  0.365223  0.671451
  2  0.334851  0.847477

In [15]:
data = {('California', 2010): 37253956,
        ('California', 2020): 39538223,
        ('New York', 2010): 19378102, 
        ('New York', 2020): 20201249,
        ('Texas', 2010): 25145561,
        ('Texas', 2020): 29145505}

pd.Series(data)

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

### Explicit <code>MultiIndex</code> Constructors

In [16]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [17]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [18]:
pd.MultiIndex(levels = [['a', 'b'], [1, 2]],
              codes = [[0, 0, 1, 1], [0, 1, 0, 1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

### <code>MultiIndex</code> Level Names

In [19]:
pop

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [20]:
pop.index.names = ['state', 'year']
pop

state       year
California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

### <code>MultiIndex</code> for Columns

In [21]:
# Hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names = ['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'],
                                     ['HR', 'Temp']],
                                     names = ['subject', 'type'])

# Mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *=10
data += 37

# Create the DataFrame
health_data = pd.DataFrame(data, index = index, columns = columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      34.0  38.2  30.0  36.3  33.0  35.6
     2      33.0  38.0  24.0  36.6  41.0  39.1
2014 1      31.0  37.3  37.0  37.4  30.0  37.9
     2      51.0  37.9  22.0  36.8  35.0  36.2

In [22]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      30.0  36.3
     2      24.0  36.6
2014 1      37.0  37.4
     2      22.0  36.8

### Indexing and Slicing a <code>MultiIndex</code>
### Multiply Indexed Series

In [23]:
pop

state       year
California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [24]:
pop['California', 2010]

37253956

In [25]:
pop['California']

year
2010    37253956
2020    39538223
dtype: int64

In [28]:
pop['California':'New york']

state       year
California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
dtype: int64

In [31]:
pop[:, 2010]

state
California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [32]:
pop[pop > 22_000_000]

state       year
California  2010    37253956
            2020    39538223
Texas       2010    25145561
            2020    29145505
dtype: int64

In [34]:
pop[['California', 'Texas']]

state       year
California  2010    37253956
            2020    39538223
Texas       2010    25145561
            2020    29145505
dtype: int64

### Multiply Indexed DataFrames

In [35]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      34.0  38.2  30.0  36.3  33.0  35.6
     2      33.0  38.0  24.0  36.6  41.0  39.1
2014 1      31.0  37.3  37.0  37.4  30.0  37.9
     2      51.0  37.9  22.0  36.8  35.0  36.2

In [36]:
health_data['Guido', 'HR']

year  visit
2013  1        30.0
      2        24.0
2014  1        37.0
      2        22.0
Name: (Guido, HR), dtype: float64

In [37]:
health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      34.0  38.2
     2      33.0  38.0

In [38]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        34.0
      2        33.0
2014  1        31.0
      2        51.0
Name: (Bob, HR), dtype: float64

In [41]:
# Will lead to an error:
# health_data.loc[(:, 1), (:, 'HR')]

In [42]:
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      34.0  30.0  33.0
2014 1      31.0  37.0  30.0

### Sorted and Unsorted Indices

In [43]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])

data = pd.Series(np.random.rand(6), index = index)

data.index.names = ['char', 'int']

data

char  int
a     1      0.578597
      2      0.318246
c     1      0.109758
      2      0.915774
b     1      0.384472
      2      0.960097
dtype: float64

In [44]:
try:
    data['a':'b']
except KeyError as e:
    print('KeyError', e)

KeyError 'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [45]:
data = data.sort_index()
data

char  int
a     1      0.578597
      2      0.318246
b     1      0.384472
      2      0.960097
c     1      0.109758
      2      0.915774
dtype: float64

In [46]:
data['a':'b']

char  int
a     1      0.578597
      2      0.318246
b     1      0.384472
      2      0.960097
dtype: float64

### Stacking and Unstacking Indices

In [49]:
pop

state       year
California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [47]:
pop.unstack(level = 0)

state  California  New York     Texas
year                                 
2010     37253956  19378102  25145561
2020     39538223  20201249  29145505

In [48]:
pop.unstack(level = 1)

year            2010      2020
state                         
California  37253956  39538223
New York    19378102  20201249
Texas       25145561  29145505

In [50]:
pop.unstack().stack()

state       year
California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

### Index Setting and Resetting

In [51]:
pop

state       year
California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [52]:
pop_flat = pop.reset_index(name = 'population')
pop_flat

state  year  population
0  California  2010    37253956
1  California  2020    39538223
2    New York  2010    19378102
3    New York  2020    20201249
4       Texas  2010    25145561
5       Texas  2020    29145505

In [53]:
pop_flat.set_index(['state', 'year'])

population
state      year            
California 2010    37253956
           2020    39538223
New York   2010    19378102
           2020    20201249
Texas      2010    25145561
           2020    29145505

### Combining Datasets: <code>concat</code> and <code>append</code>

In [54]:
import pandas as pd
import numpy as np

In [55]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

# Example DataFrame
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [56]:
class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}{1}
    """
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

### Recall: Concatenation of NumPy Arrays

In [57]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]

np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
x = [[1, 2],
     [3, 4]]

np.concatenate([x, x], axis = 1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

### Simple Concatenation with <code>pd.concat</code>

In [59]:
pd.concat?

Signature:
pd.concat(
    objs: 'Iterable[NDFrame] | Mapping[Hashable, NDFrame]',
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool' = True,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis with optional set logic
along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised.
axis : {0/'index', 1/'columns'}, defa

In [60]:
ser1 = pd.Series(['A', 'B', 'C'], index = [1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index = [4, 5, 6])

pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [61]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])

display('df1', 'df2', 'pd.concat([df1, df2])')

df1
    A   B
1  A1  B1
2  A2  B2

df2
    A   B
3  A3  B3
4  A4  B4

pd.concat([df1, df2])
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [63]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])

display('df3', 'df4', "pd.concat([df3, df4], axis = 'columns')")

df3
    A   B
0  A0  B0
1  A1  B1

df4
    C   D
0  C0  D0
1  C1  D1

pd.concat([df3, df4], axis = 'columns')
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

### Duplicate Indices

In [64]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])

y.index = x.index # make indices match

display('x', 'y', 'pd.concat([x, y])')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y])
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

In [65]:
try:
    pd.concat([x, y], verify_integrity = True)
except ValueError as e:
    print('ValueError:', e)

ValueError: Indexes have overlapping values: Int64Index([0, 1], dtype='int64')


In [66]:
display('x', 'y', 'pd.concat([x, y], ignore_index = True)')

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y], ignore_index = True)
    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [67]:
display('x', 'y', "pd.concat([x, y], keys = ['x', 'y'])")

x
    A   B
0  A0  B0
1  A1  B1

y
    A   B
0  A2  B2
1  A3  B3

pd.concat([x, y], keys = ['x', 'y'])
      A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3

### Concatenation with Joins

In [68]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])

display('df5', 'df6', 'pd.concat([df5, df6])')

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6])
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [70]:
display('df5', 'df6', "pd.concat([df5, df6], join = 'inner')")

df5
    A   B   C
1  A1  B1  C1
2  A2  B2  C2

df6
    B   C   D
3  B3  C3  D3
4  B4  C4  D4

pd.concat([df5, df6], join = 'inner')
    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [71]:
pd.concat([df5, df6.reindex(df5.columns, axis = 1)])

A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4

### The <code>append</code> Method

In [72]:
display('df1', 'df2', 'df1.append(df2)')

<string>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
<string>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.


df1
    A   B
1  A1  B1
2  A2  B2

df2
    A   B
3  A3  B3
4  A4  B4

df1.append(df2)
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [73]:
df1.append(df2)

C:\Users\vanli\AppData\Local\Temp\ipykernel_6716\3062608662.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1.append(df2)


A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4