# Essential Math for Data Science

## 4. Linear Algebra

### What is a Vector?

In [1]:
v = [3, 2]
print(v)

[3, 2]


In [2]:
import numpy as np

v = np.array([3, 2])

print(v)

[3 2]


In [6]:
import numpy as np

# Declaring a three-dimensional vector
v = np.array([4, 1, 2])

print(v)

[4 1 2]


In [7]:
# Declaring a five-dimensional vector
v = np.array([6, 1, 5, 8, 3])

print(v)

[6 1 5 8 3]


### Adding and Combining Vectors

In [9]:
from numpy import array

v = array([3, 2])
w = array([2, -1])

v_plus_w = v + w

print(v_plus_w)

[5 1]


### Scaling Vectors

In [10]:
scaled_v = v * 3
scaled_v

array([9, 6])

In [11]:
v = array([3, 1])

scaled_v = 2 * v

print(scaled_v)

[6 2]


In [12]:
scaled_v_2 = 0.5 * v

print(scaled_v_2)

[1.5 0.5]


### Matrix Vector Multiplication

In [6]:
from numpy import array

# Compose basis matrix with i-hat and j-hat
basis = array(
    [[3, 0], 
     [0, 2]]
)

# Declare vector v
v = array([1, 1])

# Create new vector by transforming v with dot product
new_v = basis.dot(v)

print(new_v)

[3 2]


In [15]:
from numpy import array

# Compose basis matrix with i-hat and j-hat
basis = array(
    [[3, 2], 
     [5, 4]]
)

# Declare vector v
v = array([3, 4])

# Create new vector by transforming v with dot product
new_v = basis.dot(v)

print(new_v)

[17 31]


In [9]:
i_hat = array([2, 0])
j_hat = array([0, 3])

# Compose basis matrix using i-hat and j-hat
# Also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()

v = array([1, 1])

new_v = basis.dot(v)

print(new_v)

[2 3]


In [12]:
i_hat = array([2, 1])
j_hat = array([0, 3])

# Compose basis matrix using i-hat and j-hat
# Also need to transpose rows into columns
basis = array([i_hat, j_hat]).transpose()

v = array([2, 1])

new_v = basis.dot(v)

print(new_v)

[4 5]


In [13]:
basis

array([[2, 0],
       [1, 3]])

In [16]:
from numpy import array

i_hat = array([2, 3])
j_hat = array([2, -1])

basis = array([i_hat, j_hat]).transpose()

v = array([2, 1])

new_v = basis.dot(v)

print(new_v)

[6 5]


### Matrix Multiplication

In [34]:
from numpy import array
import numpy as np

# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

# Combine transformations
combined = transform2 @ transform1

# Or you can use:
# combined = np.matmul(transform2, transform1)

print(f'Combined Matrix:\n{combined}\n')
#print("COMBINED MATRIX:\n {}".format(combined))

v = array([1, 2])
print(combined.dot(v))

Combined Matrix:
[[ 1 -1]
 [ 1  0]]

[-1  1]


In [35]:
rotated = transform1.dot(v)
sheared = transform2.dot(rotated)
print(sheared)

[-1  1]


In [36]:
from numpy import array

# Transformation 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

# Transformation 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

# Combine transformations
combined = transform1 @ transform2

print(f'Combined Matrix:\n{combined}\n')
#print("COMBINED MATRIX:\n {}".format(combined))

v = array([1, 2])
print(combined.dot(v))

Combined Matrix:
[[ 0 -1]
 [ 1  1]]

[-2  3]


### Determinants

In [37]:
from numpy.linalg import det
from numpy import array

i_hat = array([3, 0])
j_hat = array([0, 2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

6.0


In [38]:
from numpy.linalg import det
from numpy import array

i_hat = array([1, 0])
j_hat = array([1, 1])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

1.0


In [39]:
from numpy.linalg import det
from numpy import array

i_hat = array([-2, 1])
j_hat = array([1, 2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

-5.000000000000001


In [40]:
from numpy.linalg import det
from numpy import array

i_hat = array([-2, 1])
j_hat = array([3, -1.5])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

0.0


### Systems of Equations and Inverse Matrices

In [21]:
from numpy import array
from numpy.linalg import inv

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = array([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = array([
    44,
    56,
    72
])

X = inv(A).dot(B)

print(X)
print(f'\nx = {int(X[0])}\ny = {int(X[1])}\nz = {int(X[2])}')

INVERSE: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
IDENTITY: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


In [21]:
from numpy import array
from numpy.linalg import inv

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = array([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = array([
    44,
    56,
    72
])

X = inv(A).dot(B)

print(X)
print(f'\nx = {int(X[0])}\ny = {int(X[1])}\nz = {int(X[2])}')

INVERSE: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
IDENTITY: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


In [23]:
from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = Matrix([
    44,
    56,
    72
])

X = A.inv() * B

print(X)

Matrix([[2], [34], [-8]])


### Eigenvectors and Eigenvalues