# Essential Math for Data Science

## 4. Linear Algebra

### What is a Vector?

In [1]:
v = [3, 2]
print(v)

[3, 2]


In [2]:
import numpy as np

v = np.array([3, 2])

print(v)

[3 2]


In [6]:
import numpy as np

# Declaring a three-dimensional vector
v = np.array([4, 1, 2])

print(v)

[4 1 2]


In [7]:
# Declaring a five-dimensional vector
v = np.array([6, 1, 5, 8, 3])

print(v)

[6 1 5 8 3]


### Adding and Combining Vectors

In [9]:
from numpy import array

v = array([3, 2])
w = array([2, -1])

v_plus_w = v + w

print(v_plus_w)

[5 1]


### Scaling Vectors

In [10]:
scaled_v = v * 3
scaled_v

array([9, 6])

In [11]:
v = array([3, 1])

scaled_v = 2 * v

print(scaled_v)

[6 2]


In [12]:
scaled_v_2 = 0.5 * v

print(scaled_v_2)

[1.5 0.5]
