# 01. What is Numpy

NumPy is the fundamental package for scientific computing with Python. 
It is a package that provides high-performance vector, matrix and higher-dimensional data structures for Python. 
It is implemented in C and Fortran so when calculations are **vectorized**, performance is very good.

So, in a nutshell:

* a powerful Python extension for N-dimensional array
* a tool for integrating C/C++ and Fortran code
* designed for scientific computation: linear algebra and Signal Analysis

If you are a MATLAB&reg; user we recommend to read [Numpy for MATLAB Users](http://www.scipy.org/NumPy_for_Matlab_Users) and [Benefit of Open Source Python versus commercial packages](http://www.scipy.org/NumPyProConPage). 

I'm a supporter of the **Open Science Movement**, thus I humbly suggest you to take a look at the [Science Code Manifesto](http://sciencecodemanifesto.org/)

# Getting Started with Numpy Arrays

NumPy's main object is the **homogeneous** ***multidimensional array***. It is a table of elements (usually numbers), all of the same type. 

In Numpy dimensions are called **axes**. 

The number of axes is called **rank**. 

The most important attributes of an ndarray object are:

* **ndarray.ndim**     - the number of axes (dimensions) of the array. 
* **ndarray.shape**    - the dimensions of the array. For a matrix with n rows and m columns, shape will be (n,m). 
* **ndarray.size**     - the total number of elements of the array. 
* **ndarray.dtype**    - numpy.int32, numpy.int16, and numpy.float64 are some examples. 
* **ndarray.itemsize** - the size in bytes of elements of the array. For example, elements of type float64 has itemsize 8 (=64/8) 

To use `numpy` need to import the module it using of example:

In [1]:
import numpy as np  # naming import convention

### Terminology Assumption

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 

### Reference Documentation

* On the web: [http://docs.scipy.org](http://docs.scipy.org)/

* Interactive help:

In [2]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if __array__ returns a copy, if obj is a nested sequence,
    or if a copy is needed to satisfy any of the other requirements
    (`dtype`, `order`, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly created array will be in C order (row major) unless 'F' is
    specified, in which case it will be in Fortran order (c

If you're looking for something

## Numpy Array Object

`NumPy` has a multidimensional array object called ndarray. It consists of two parts as follows:
   
   * The actual data
   * Some metadata describing the data
    
    
The majority of array operations leave the raw data untouched. The only aspect that changes is the metadata.

<img src="images/ndarray_with_details.png" />

## Creating `numpy` arrays

There are a number of ways to initialize new numpy arrays, for example from

* a Python list or tuples
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [3]:
v = np.array([1, 2, 3, 4])
v

array([1, 2, 3, 4])

In [4]:
M = np.array([[1, 2], [3, 4]])
M

array([[1, 2],
       [3, 4]])

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [5]:
print('Type of v: ', type(v))
print('Type of M: ', type(M))

Type of v:  <class 'numpy.ndarray'>
Type of M:  <class 'numpy.ndarray'>


The difference between the `v` and `M` arrays is only their shapes. 

To do so, we could use the `numpy.shape` function:

In [6]:
print('Shape of v: ', np.shape(v))
print('Shape of M: ', np.shape(M))

Shape of v:  (4,)
Shape of M:  (2, 2)


Alternatively, we can get information about the shape of an array by using the `ndarray.shape` **property** :

In [7]:
v.shape, M.shape

((4,), (2, 2))

Equivalently, we can get information about the **size** of the two `ndarrays`, namely the *total number of elements* in the array.

In [8]:
print('Size of v:', v.size)
print('Size of M:', M.size)

Size of v: 4
Size of M: 4


#### More properties of the `numpy array`

In [9]:
M.itemsize # bytes per element

4

In [10]:
M.nbytes # number of bytes

16

In [11]:
M.ndim # number of dimensions

2

## Using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit python lists. 

Instead we can use one of the many **functions** in `numpy` that generates arrays of different forms. 

Some of the more common are: 

* `np.arange`; 
* `np.linspace`; 
* `np.logspace`; 
* `np.mgrid`;
* `np.random.rand`;
* `np.diag`;
* `np.zeros`;
* `np.ones`;
* `np.empty`;
* `np.tile`.

### `np.arange`

In [12]:
x = np.arange(0, 10, 1) 
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
# floating point step-wise range generatation
x = np.arange(-1, 1, 0.1)  
print(x)

[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]


### `np.linspace` and `np.logspace`

In [14]:
# using linspace, both end points **ARE included**
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [15]:
np.logspace(0, np.e**2, 10, base=np.e)

array([1.00000000e+00, 2.27278564e+00, 5.16555456e+00, 1.17401982e+01,
       2.66829540e+01, 6.06446346e+01, 1.37832255e+02, 3.13263169e+02,
       7.11980032e+02, 1.61817799e+03])

### `np.mgrid`

In [16]:
x, y = np.mgrid[0:5, 0:5]  # similar to meshgrid in MATLAB

In [17]:
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [18]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### `np.random.rand` & `np.random.randn`

In [19]:
np.random.seed(4)

In [20]:
# uniform random numbers in [0,1]
R = np.random.rand(5,5)

In [21]:
R

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599, 0.69772882],
       [0.2160895 , 0.97627445, 0.00623026, 0.25298236, 0.43479153],
       [0.77938292, 0.19768507, 0.86299324, 0.98340068, 0.16384224],
       [0.59733394, 0.0089861 , 0.38657128, 0.04416006, 0.95665297],
       [0.43614665, 0.94897731, 0.78630599, 0.8662893 , 0.17316542]])

In [22]:
R

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599, 0.69772882],
       [0.2160895 , 0.97627445, 0.00623026, 0.25298236, 0.43479153],
       [0.77938292, 0.19768507, 0.86299324, 0.98340068, 0.16384224],
       [0.59733394, 0.0089861 , 0.38657128, 0.04416006, 0.95665297],
       [0.43614665, 0.94897731, 0.78630599, 0.8662893 , 0.17316542]])

In [23]:
# standard normal distributed random numbers
np.random.randn(5,5)

array([[ 0.16951775, -0.71522547,  0.52533388, -0.74738768,  0.74981904],
       [-2.4598148 ,  0.03600369,  0.72612944,  1.43327736,  2.6547994 ],
       [-1.21166587,  1.69268959, -1.14031579,  1.65688784,  1.31929701],
       [ 0.61136545, -0.441491  , -1.13908785,  1.98495133,  0.02693565],
       [ 0.35880669, -1.61454139,  0.82448138,  0.26043704,  1.37718202]])

### `np.diag`

In [24]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [25]:
# diagonal with offset from the main diagonal
np.diag([1,2,3], k=-1)[::-1]

array([[0, 0, 3, 0],
       [0, 2, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0]])

### `np.eye`

In [26]:
# a diagonal matrix with ones on the main diagonal
np.eye(3, dtype='int')  # 3 is the 

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### `np.zeros` and `np.ones`

In [27]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### DIY

***Try by yourself*** the following commands:

    np.zeros((3,4))
    np.ones((3,4))
    np.empty((2,3))
    np.eye(5)
    np.diag(np.arange(5))
    np.tile(np.array([[6, 7], [8, 9]]), (2, 2))

In [29]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.empty((2, 3), dtype='str')

array([['', '', ''],
       ['', '', '']], dtype='<U1')

In [32]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [33]:
np.diag(np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [34]:
np.tile(np.array([[6, 7], [8, 9]]), (2, 2))

array([[6, 7, 6, 7],
       [8, 9, 8, 9],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

## So, why is it useful then?

So far the `numpy.ndarray` looks awefully much like a Python **list** (or **nested list**). 

*Why not simply use Python lists for computations instead of creating a new array type?*

There are several reasons:

* Python lists are very general. 
    - They can contain any kind of object. 
    - They are dynamically typed. 
    - They do not support mathematical functions such as matrix and dot multiplications, etc. 
    - Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
    
    
* Numpy arrays are **statically typed** and **homogeneous**. 
    - The type of the elements is determined when array is created.
    
    
* Numpy arrays are memory efficient.
    - Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

In [35]:
import numpy as np

In [36]:
L = range(100000)

In [37]:
%timeit [i**2 for i in L]

27.2 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [38]:
a = np.arange(100000)

In [39]:
%timeit a**2

66.2 µs ± 2.35 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [40]:
%timeit [element**2 for element in a]

23.2 ms ± 1.16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


---

## Exercises

### Simple arrays

* Create simple one and two dimensional arrays. First, redo the examples
from above. And then create your own.

* Use the functions `len`, `shape` and `ndim` on some of those arrays and
observe their output.

1D array:

In [41]:
ex_array_1 = np.random.randn(1)
ex_array_1

array([-1.37307059])

2D array:

In [42]:
ex_array_2 = np.random.randn(2, 2)
ex_array_2

array([[-0.00993354, -1.38947805],
       [ 1.22956251, -0.25388263]])

In [43]:
print(len(ex_array_1))
print(len(ex_array_2))

1
2


In [44]:
print(ex_array_1.shape)
print(ex_array_2.shape)

(1,)
(2, 2)


In [45]:
print(ex_array_1.ndim)
print(ex_array_2.ndim)

1
2


### Creating arrays using functions

* Experiment with `arange`, `linspace`, `ones`, `zeros`, `eye` and `diag`.

* Create different kinds of arrays with random numbers.

* Try setting the seed before creating an array with random values 
    - *hint*: use `np.random.seed`

* Look at the function `np.empty`. What does it do? When might this be
useful?

---

## Basic Data Types

    bool             | This stores boolean (True or False) as a bit

    inti             | This is a platform integer (normally either int32 or int64)
    int8             | This is an integer ranging from -128 to 127
    int16            | This is an integer ranging from -32768 to 32767
    int32            | This is an integer ranging from -2 ** 31 to 2 ** 31 -1
    int64            | This is an integer ranging from -2 ** 63 to 2 ** 63 -1
    
    uint8            | This is an unsigned integer ranging from 0 to 255
    uint16           | This is an unsigned integer ranging from 0 to 65535
    uint32           | This is an unsigned integer ranging from 0 to 2 ** 32 - 1
    uint64           | This is an unsigned integer ranging from 0 to 2 ** 64 - 1

    float16          | This is a half precision float with sign bit, 5 bits exponent, and 10 bits mantissa
    float32          | This is a single precision float with sign bit, 8 bits exponent, and 23 bits mantissa
    float64 or float | This is a double precision float with sign bit, 11 bits exponent, and 52 bits mantissa
    complex64        | This is a complex number represented by two 32-bit floats (real and imaginary components)
    complex128       | This is a complex number represented by two 64-bit floats (real and imaginary components)
    (or complex)


## Numerical Types and Representation

The **numerical dtype** of an array should be selected very carefully, as it directly affects the numerical representation of elements, that is: 

   * the number of **bytes used; 
   * the *numerical range*

So, then: **What happens if I try to represent a number that is Out of range?**

Let's have a go with **integers**, i.e., `int8` and `uint8`

In [46]:
x = np.zeros(4, 'int8')  # Integer ranging from -128 to 127
x

array([0, 0, 0, 0], dtype=int8)

In [47]:
x[0] = 127
x

array([127,   0,   0,   0], dtype=int8)

In [48]:
x[0] = 128
x

array([-128,    0,    0,    0], dtype=int8)

In [49]:
x[1] = 129
x

array([-128, -127,    0,    0], dtype=int8)

In [50]:
x[2] = 257  # i.e. (128 x 2) + 1
x

array([-128, -127,    1,    0], dtype=int8)

In [51]:
ux = np.zeros(4, 'uint8')  # Integer ranging from 0 to 255
ux

array([0, 0, 0, 0], dtype=uint8)

In [52]:
ux[0] = 255  # from 0 to 255
ux[1] = 256  # 256 - 255 = 1 or 0
ux[2] = 257  # 257 - 255 = 2 or 1
ux[3] = 513  # (256 x 2) + 1 
ux

array([255,   0,   1,   1], dtype=uint8)

---

# Exercises - Basic Numpy

## Exercise 1. Create an array containing integers from $2$ to $2^6$

#### Hint: use Python `range` function

In [53]:
ex1 = np.array(range(2, 2**6 + 1))
ex1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64])

## Exercise 2. Print `ndarray` attributes and properties
(e.g. `type`, `dtype`, `shape...`) using previous on

In [54]:
print(
    f'Array\n{ex1}'
    f'\n\n'
    f'Type\n{type(ex1)}'                # type()
    f'\n\n'
    f'Data type\n{ex1.dtype}'           # dtype
    f'\n\n'
    f'Shape\n{ex1.shape}'               # shape
    f'\n\n'
    f'Number of dimensions\n{ex1.ndim}' # ndim
    f'\n\n'
    f'Number of elements\n{ex1.size}'   # size
    f'\n\n'
    f'Item size\n{ex1.itemsize}'        # itemsize
)

Array
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]

Type
<class 'numpy.ndarray'>

Data type
int32

Shape
(63,)

Number of dimensions
1

Number of elements
63

Item size
4


## Exercise 3. Create a 3x3 Matrix array and fill it with integer numbers

In [55]:
matrix_3d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Exercise 4. Create a Matrix of any size and fill it with random numbers

### Hint: take a look at `numpy.random.rand`

In [56]:
random_matrix = np.random.randn(5, 4) 
random_matrix

array([[ 0.85576984, -0.17599712, -1.69610226, -0.95617171],
       [ 1.15563935,  0.24133141,  0.27677085,  1.04420738],
       [ 0.18173901, -0.77604419,  0.82242392, -0.90004667],
       [ 0.0362415 ,  0.97073319, -0.65066811,  0.15493329],
       [-1.0765125 ,  0.11634145, -1.55579813,  1.3072029 ]])

---

# Indexing

### Setting up the data

In [57]:
np.random.seed(42)  # Setting the random seed

In [58]:
# a vector: the argument to the array function is a Python list
v = np.random.rand(10)
v

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [59]:
# a matrix: the argument to the array function is a nested Python list
M = np.random.rand(10, 2)
M

array([[0.02058449, 0.96990985],
       [0.83244264, 0.21233911],
       [0.18182497, 0.18340451],
       [0.30424224, 0.52475643],
       [0.43194502, 0.29122914],
       [0.61185289, 0.13949386],
       [0.29214465, 0.36636184],
       [0.45606998, 0.78517596],
       [0.19967378, 0.51423444],
       [0.59241457, 0.04645041]])

We can index elements in an array using the square bracket and indices:

In [60]:
# v is a vector, and has only one dimension, taking one index
v[0]

0.3745401188473625

In [61]:
# M is a matrix, or a 2 dimensional array, taking two indices 
M[1, 1]

0.21233911067827616

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [62]:
M[1] 

array([0.83244264, 0.21233911])

The same thing can be achieved with using `:` instead of an index: 

In [63]:
M[1, :] # row 1

array([0.83244264, 0.21233911])

In [64]:
M[:, 1] # column 1

array([0.96990985, 0.21233911, 0.18340451, 0.52475643, 0.29122914,
       0.13949386, 0.36636184, 0.78517596, 0.51423444, 0.04645041])

We can assign new values to elements in an array using indexing:

In [65]:
M[0, 0] = 1

In [66]:
M

array([[1.        , 0.96990985],
       [0.83244264, 0.21233911],
       [0.18182497, 0.18340451],
       [0.30424224, 0.52475643],
       [0.43194502, 0.29122914],
       [0.61185289, 0.13949386],
       [0.29214465, 0.36636184],
       [0.45606998, 0.78517596],
       [0.19967378, 0.51423444],
       [0.59241457, 0.04645041]])

In [67]:
# also works for rows and columns
M[1, :] = 0
M[:, 1] = -1

In [68]:
M

array([[ 1.        , -1.        ],
       [ 0.        , -1.        ],
       [ 0.18182497, -1.        ],
       [ 0.30424224, -1.        ],
       [ 0.43194502, -1.        ],
       [ 0.61185289, -1.        ],
       [ 0.29214465, -1.        ],
       [ 0.45606998, -1.        ],
       [ 0.19967378, -1.        ],
       [ 0.59241457, -1.        ]])

## Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [69]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [70]:
a[1:3]

array([2, 3])

Array slices are **mutable**: if they are assigned a new value the original array from which the slice was extracted is modified:

In [71]:
a[1:3] = [-2,-3]

a

array([ 1, -2, -3,  4,  5])

* We can omit any of the three parameters in `M[lower:upper:step]`:

In [72]:
a[::] # lower, upper, step all take the default values

array([ 1, -2, -3,  4,  5])

In [73]:
a[::2] # step is 2, lower and upper defaults to the beginning and end of the array

array([ 1, -3,  5])

In [74]:
a[:3] # first three elements

array([ 1, -2, -3])

In [75]:
a[3:] # elements from index 3

array([4, 5])

* Negative indices counts from the end of the array (positive index from the begining):

In [76]:
a = np.array([1, 2, 3, 4, 5])

In [77]:
a[-1] # the last element in the array

5

In [78]:
a[-3:] # the last three elements

array([3, 4, 5])

* Index slicing works exactly the same way for multidimensional arrays:

In [80]:
A = np.array([[n+m*10 for n in range(5)] 
              for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [81]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [82]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

## Fancy indexing

Fancy indexing is the name for when an array or list is used in-place of an index: 

In [91]:
print(A)

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


In [92]:
row_indices = [1, 2, 3]
print(A[row_indices])

[[10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]]


In [93]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
print(A[row_indices, col_indices])

[11 22 34]


* We can also index **masks**: 

    - If the index mask is an Numpy array of with data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position each element: 

In [94]:
b = np.array([n for n in range(5)])
b

array([0, 1, 2, 3, 4])

In [95]:
row_mask = np.array([True, False, True, False, False])
b[row_mask]

array([0, 2])

* Alternatively:

In [97]:
row_mask = np.array([1, 0, 1, 0, 0], dtype=bool)
b[row_mask]

array([0, 2])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [105]:
x = np.arange(0, 10+0.1, 0.1)
x

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [106]:
mask = (x >= 8)

x[mask]

array([ 8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ,
        9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. ])

In [99]:
mask = (5 < x)

mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [100]:
x[mask]

array([5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

Alternatively, we can use the condition (mask) array directly within brackets to index the array

In [101]:
x[(5 < x)]

array([5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

---

# Exercises on Indexing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array

#### Exercise 1 

Generate a three-dimensional array of any size containing random numbers taken from an uniform distribution (_guess the numpy function in `np.random`_). Then print out separately the first entry along the three axis (i.e. `x, y, z`)  

Hint: Slicing with numpy arrays works quite like Python lists

In [109]:
ex_1 = np.random.rand(3, 3, 4)
print(ex_1)

[[[0.31435598 0.50857069 0.90756647 0.24929223]
  [0.41038292 0.75555114 0.22879817 0.07697991]
  [0.28975145 0.16122129 0.92969765 0.80812038]]

 [[0.63340376 0.87146059 0.80367208 0.18657006]
  [0.892559   0.53934224 0.80744016 0.8960913 ]
  [0.31800347 0.11005192 0.22793516 0.42710779]]

 [[0.81801477 0.86073058 0.00695213 0.5107473 ]
  [0.417411   0.22210781 0.11986537 0.33761517]
  [0.9429097  0.32320293 0.51879062 0.70301896]]]


In [114]:
print('First entry along the x-axis:')
print(ex_1[0, :, :])

print('\nFirst entry along the y-axis:')
print(ex_1[:, 0, :])

print('\nFirst entry along the z-axis:')
print(ex_1[:, :, 0])

First entry along the x-axis:
[[0.31435598 0.50857069 0.90756647 0.24929223]
 [0.41038292 0.75555114 0.22879817 0.07697991]
 [0.28975145 0.16122129 0.92969765 0.80812038]]

First entry along the y-axis:
[[0.31435598 0.50857069 0.90756647 0.24929223]
 [0.63340376 0.87146059 0.80367208 0.18657006]
 [0.81801477 0.86073058 0.00695213 0.5107473 ]]

First entry along the z-axis:
[[0.31435598 0.41038292 0.28975145]
 [0.63340376 0.892559   0.31800347]
 [0.81801477 0.417411   0.9429097 ]]


#### Exercise 2

Create a vector and print out elements in reverse order

Hint: Use slicing for this exercise

In [120]:
vector = np.random.rand(20)
print(vector)

[0.6454723  0.17711068 0.94045858 0.95392858 0.91486439 0.3701587
 0.01545662 0.92831856 0.42818415 0.96665482 0.96361998 0.85300946
 0.29444889 0.38509773 0.85113667 0.31692201 0.16949275 0.55680126
 0.93615477 0.6960298 ]


In [122]:
vector[::-1]

array([0.6960298 , 0.93615477, 0.55680126, 0.16949275, 0.31692201,
       0.85113667, 0.38509773, 0.29444889, 0.85300946, 0.96361998,
       0.96665482, 0.42818415, 0.92831856, 0.01545662, 0.3701587 ,
       0.91486439, 0.95392858, 0.94045858, 0.17711068, 0.6454723 ])

In [123]:
vector_2 = np.arange(0, 11)
print(vector_2)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [124]:
vector_2[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### Exercise 3 ←←←←←←←←←←←←←←←←← stopped here

Generate a $7 \times 7$ matrix and replace all the elements in odd rows and even columns with `1`.

Hint: Use slicing to solve this exercise!

Note: Take a look at the original matrix, then.

In [132]:
matrix = np.random.randn(7, 7)
matrix

array([[-0.33450124, -0.47494531, -0.65332923,  1.76545424,  0.40498171,
        -1.26088395,  0.91786195],
       [ 2.1221562 ,  1.03246526, -1.51936997, -0.48423407,  1.26691115,
        -0.70766947,  0.44381943],
       [ 0.77463405, -0.92693047, -0.05952536, -3.24126734, -1.02438764,
        -0.25256815, -1.24778318],
       [ 1.6324113 , -1.43014138, -0.44004449,  0.13074058,  1.44127329,
        -1.43586215,  1.16316375],
       [ 0.01023306, -0.98150865,  0.46210347,  0.1990597 , -0.60021688,
         0.06980208, -0.3853136 ],
       [ 0.11351735,  0.66213067,  1.58601682, -1.2378155 ,  2.13303337,
        -1.9520878 , -0.1517851 ],
       [ 0.58831721,  0.28099187, -0.62269952, -0.20812225, -0.49300093,
        -0.58936476,  0.8496021 ]])

In [135]:
matrix[:] = 777

In [136]:
matrix

array([[777., 777., 777., 777., 777., 777., 777.],
       [777., 777., 777., 777., 777., 777., 777.],
       [777., 777., 777., 777., 777., 777., 777.],
       [777., 777., 777., 777., 777., 777., 777.],
       [777., 777., 777., 777., 777., 777., 777.],
       [777., 777., 777., 777., 777., 777., 777.],
       [777., 777., 777., 777., 777., 777., 777.]])

In [137]:
matrix[::2]

array([[777., 777., 777., 777., 777., 777., 777.],
       [777., 777., 777., 777., 777., 777., 777.],
       [777., 777., 777., 777., 777., 777., 777.],
       [777., 777., 777., 777., 777., 777., 777.]])

In [139]:
matrix_2 = np.zeros((7, 7), dtype=int)
matrix_2

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [141]:
matrix_2[::2, 1::2] = 1

In [142]:
print(matrix_2)

[[0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0]
 [0 1 0 1 0 1 0]]


In [146]:
matrix_3 = np.array(matrix_2)
matrix_3

array([[0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0]])

In [147]:
matrix_3[(x > 0)]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 101

**Use fancy indexing** to get all the elements of the previous matrix that are equals to `1`

#### Exercise 4

Generate a `10 x 10` matrix of numbers `A`. Then, generate a numpy array of integers in range `1-9`. Pick `5` random values (with no repetition) from this array and use these values to extract rows from the original matrix `A`.

#### Exercise 5

Repeat the previous exercise but this time extract columns from `A`

#### Exercise 6

Generate an array of numbers from `0` to `20` with step `0.5`. 
Extract all the values greater than a randomly generated number in the same range.

Hint: Try to write the condition as an expression and save it to a variable. Then, use this variable in square brackets to index.... this is when the magic happens!