# Notes (02)

In [5]:
import numpy as np
from scipy import sparse

# 02. Representation of Data (for Machine Learning)

In [3]:
np.random.seed(42)
X = np.random.random((10, 5))
X[X < 0.7] = 0
print(X)

[[0.         0.95071431 0.73199394 0.         0.        ]
 [0.         0.         0.86617615 0.         0.70807258]
 [0.         0.96990985 0.83244264 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.78517596 0.         0.         0.         0.        ]
 [0.         0.         0.         0.94888554 0.96563203]
 [0.80839735 0.         0.         0.         0.        ]
 [0.         0.         0.         0.9093204  0.        ]
 [0.         0.         0.         0.         0.        ]]


In [9]:
print(X)

[[0.         0.95071431 0.73199394 0.         0.        ]
 [0.         0.         0.86617615 0.         0.70807258]
 [0.         0.96990985 0.83244264 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.78517596 0.         0.         0.         0.        ]
 [0.         0.         0.         0.94888554 0.96563203]
 [0.80839735 0.         0.         0.         0.        ]
 [0.         0.         0.         0.9093204  0.        ]
 [0.         0.         0.         0.         0.        ]]


In [10]:
X_csr = sparse.csr_matrix(X)
print(X_csr)

  (0, 1)	0.9507143064099162
  (0, 2)	0.7319939418114051
  (1, 2)	0.8661761457749352
  (1, 4)	0.7080725777960455
  (2, 1)	0.9699098521619943
  (2, 2)	0.8324426408004217
  (5, 0)	0.7851759613930136
  (6, 3)	0.9488855372533332
  (6, 4)	0.9656320330745594
  (7, 0)	0.8083973481164611
  (8, 3)	0.9093204020787821


In [11]:
print(X_csr.toarray())

[[0.         0.95071431 0.73199394 0.         0.        ]
 [0.         0.         0.86617615 0.         0.70807258]
 [0.         0.96990985 0.83244264 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.78517596 0.         0.         0.         0.        ]
 [0.         0.         0.         0.94888554 0.96563203]
 [0.80839735 0.         0.         0.         0.        ]
 [0.         0.         0.         0.9093204  0.        ]
 [0.         0.         0.         0.         0.        ]]


In [30]:
print(X_csr.shape[1])

5


In [56]:
y = np.random.random(5)
y

array([0.65998405, 0.8172222 , 0.55520081, 0.52965058, 0.24185229])

In [59]:
print(X_csr)

  (0, 1)	0.9507143064099162
  (0, 2)	0.7319939418114051
  (1, 2)	0.8661761457749352
  (1, 4)	0.7080725777960455
  (2, 1)	0.9699098521619943
  (2, 2)	0.8324426408004217
  (5, 0)	0.7851759613930136
  (6, 3)	0.9488855372533332
  (6, 4)	0.9656320330745594
  (7, 0)	0.8083973481164611
  (8, 3)	0.9093204020787821


In [ ]:
z1 = X_csr.dot(y)
z1

array([1.18334847, 0.65215067, 1.25480469, 0.        , 0.        ,
       0.51820361, 0.73611809, 0.53352935, 0.48162208, 0.        ])

In [61]:
X

array([[0.        , 0.95071431, 0.73199394, 0.        , 0.        ],
       [0.        , 0.        , 0.86617615, 0.        , 0.70807258],
       [0.        , 0.96990985, 0.83244264, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.78517596, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.94888554, 0.96563203],
       [0.80839735, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.9093204 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [60]:
z2 = X.dot(y)
z2

array([1.18334847, 0.65215067, 1.25480469, 0.        , 0.        ,
       0.51820361, 0.73611809, 0.53352935, 0.48162208, 0.        ])

In [70]:
example_1 = np.arange(0, 5)
example_2 = np.arange(0, 5)
example_3 = np.arange(0+10, 5+10)

np.allclose(example_1, example_2)

True

In [71]:
np.allclose(example_2, example_3)

False