# Notes (01–...)

In [1]:
import numpy as np

# 01. What is Numpy

In [2]:
age = [10, 18, 61, 52, 13]

In [3]:
ex_array = np.array(age)

In [6]:
ex_array

array([10, 18, 61, 52, 13])

In [13]:
print(type(ex_array))
print(type(age))

<class 'numpy.ndarray'>
<class 'list'>


In [17]:
ex_array_1 = np.array([10, 18, 61, 52, 13])
ex_array_1

array([10, 18, 61, 52, 13])

In [18]:
ex_array_2 = np.array([[10, 17, 13], [61, 52, 43]])
ex_array_2

array([[10, 17, 13],
       [61, 52, 43]])

In [28]:
print(np.shape(ex_array_1))
print(np.shape(ex_array_2))

(5,)
(2, 3)


In [31]:
print(ex_array_1.shape)
print(ex_array_2.shape)

(5,)
(2, 3)


In [32]:
ex_array_1.shape, ex_array_2.shape

((5,), (2, 3))

In [33]:
print(ex_array_1.size)
print(ex_array_2.size)

5
6


In [34]:
print(ex_array_1.itemsize)
print(ex_array_2.itemsize)

4
4


In [35]:
print(ex_array_1.nbytes)
print(ex_array_2.nbytes)

20
24


In [36]:
print(ex_array_1.ndim)
print(ex_array_2.ndim)

1
2


In [37]:
age_tuple = (10, 18, 61, 52, 13)

In [38]:
ex_array_1_tuple = np.array(age_tuple)
ex_array_1_tuple

array([10, 18, 61, 52, 13])

In [52]:
ex_array_1_func = np.arange(1, 100+1, 1)
print(ex_array_1_func)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [53]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is Fals

In [59]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [60]:
np.logspace?

Signature:
np.logspace(
    start,
    stop,
    num=50,
    endpoint=True,
    base=10.0,
    dtype=None,
    axis=0,
)
Docstring:
Return numbers spaced evenly on a log scale.

In linear space, the sequence starts at ``base ** start``
(`base` to the power of `start`) and ends with ``base ** stop``
(see `endpoint` below).

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    ``base ** start`` is the starting value of the sequence.
stop : array_like
    ``base ** stop`` is the final value of the sequence, unless `endpoint`
    is False.  In that case, ``num + 1`` values are spaced over the
    interval in log-space, of which all but the last (a sequence of
    length `num`) are returned.
num : integer, optional
    Number of samples to generate.  Default is 50.
endpoint : boolean, optional
    If true, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
base : array_like, optional
    The

In [63]:
np.logspace(1, 10, 5, base=np.e)

array([2.71828183e+00, 2.57903399e+01, 2.44691932e+02, 2.32157241e+03,
       2.20264658e+04])