# Notes (04–05)

# 04. Introduction

In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [4]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
arr_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print(arr_4d)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


In [6]:
import pandas as pd

In [7]:
sales_data = pd.read_csv('./data/blooth_sales_data.csv')

In [28]:
pd.set_option('display.max_rows', 9999999999)  # change presets for data preview
sales_data.head(10)

name    birthday                           customer  \
0  Pasquale  1967-09-02                    Electronics Inc   
1     India  1968-12-13         Electronics Resource Group   
2     Wayne  1992-09-10      East Application Contract Inc   
3      Cori  1986-11-05                  Signal Industries   
4     Chang  1972-04-23              Star Alpha Industries   
5    Weldon  1953-03-17             Network Application Co   
6      Sung  1977-10-23  Omega Pacific Future Incorporated   
7     Emily  1982-07-02              Medicine Incorporated   
8   Cornell  1963-07-02     Technology Direct Star Limited   
9     Ervin  1977-10-14                    Provider Agency   

                    orderdate            product  units  unitprice  
0  2016-07-17 13:48:03.156566    Thriller record      2      13.27  
1  2016-07-06 13:48:03.156596            Corolla     26   24458.69  
2  2016-07-22 13:48:03.156618       Rubik’s Cube     41      15.79  
3  2016-07-23 13:48:03.156638             iPhone     16     584.01  
4  2016-07-16 13:48:03.156657  Harry Potter book      4      25.69  
5  2016-07-22 13:48:03.156678            Lipitor      1      11.22  
6  2016-07-09 13:48:03.156698        PlayStation     25     294.90  
7  2016-07-16 13:48:03.156717    Thriller record      5      18.27  
8  2016-07-08 13:48:03.156735       Rubik’s Cube     35      15.98  
9  2016-07-19 13:48:03.156754          Star Wars     24      11.50

In [31]:
sales_data.dtypes

name          object
birthday      object
customer      object
orderdate     object
product       object
units          int64
unitprice    float64
dtype: object

In [39]:
sales_data['birthday'] = pd.to_datetime(sales_data['birthday'])
sales_data.head(5)

name   birthday                       customer  \
0  Pasquale 1967-09-02                Electronics Inc   
1     India 1968-12-13     Electronics Resource Group   
2     Wayne 1992-09-10  East Application Contract Inc   
3      Cori 1986-11-05              Signal Industries   
4     Chang 1972-04-23          Star Alpha Industries   

                    orderdate            product  units  unitprice  
0  2016-07-17 13:48:03.156566    Thriller record      2      13.27  
1  2016-07-06 13:48:03.156596            Corolla     26   24458.69  
2  2016-07-22 13:48:03.156618       Rubik’s Cube     41      15.79  
3  2016-07-23 13:48:03.156638             iPhone     16     584.01  
4  2016-07-16 13:48:03.156657  Harry Potter book      4      25.69

In [40]:
sales_data.dtypes

name                 object
birthday     datetime64[ns]
customer             object
orderdate            object
product              object
units                 int64
unitprice           float64
dtype: object

In [41]:
sales_data['orderdate'] = pd.to_datetime(sales_data['orderdate'])
sales_data.head(5)

name   birthday                       customer  \
0  Pasquale 1967-09-02                Electronics Inc   
1     India 1968-12-13     Electronics Resource Group   
2     Wayne 1992-09-10  East Application Contract Inc   
3      Cori 1986-11-05              Signal Industries   
4     Chang 1972-04-23          Star Alpha Industries   

                   orderdate            product  units  unitprice  
0 2016-07-17 13:48:03.156566    Thriller record      2      13.27  
1 2016-07-06 13:48:03.156596            Corolla     26   24458.69  
2 2016-07-22 13:48:03.156618       Rubik’s Cube     41      15.79  
3 2016-07-23 13:48:03.156638             iPhone     16     584.01  
4 2016-07-16 13:48:03.156657  Harry Potter book      4      25.69

In [42]:
sales_data.dtypes

name                 object
birthday     datetime64[ns]
customer             object
orderdate    datetime64[ns]
product              object
units                 int64
unitprice           float64
dtype: object

In [44]:
# sales_data['birthday', 'orderdate'] = sales_data[['birthday', 'orderdate']].apply(pd.to_datetime)

In [20]:
sales_data.tail()

name    birthday                   customer  \
995     Ethan  1952-12-08     Application Industries   
996   Rudolph  1959-10-15  Network Software West Inc   
997  Annmarie  1982-06-04       Atlantic Corporation   
998     Chang  1984-02-05  Venture Alpha Corporation   
999     Ervin  1977-10-14            Provider Agency   

                      orderdate            product  units  unitprice  
995  2016-07-21 13:48:03.177885  Harry Potter book     39      24.40  
996  2016-07-19 13:48:03.177903       Rubik’s Cube      9      15.11  
997  2016-07-13 13:48:03.177924    Thriller record     19       9.16  
998  2016-07-13 13:48:03.177943  Harry Potter book     24      28.21  
999  2016-07-09 13:48:03.177962             iPhone     39     663.83

In [21]:
len(sales_data)

1000

In [22]:
sales_data.shape

(1000, 7)

In [46]:
sales_data.count()

name         1000
birthday     1000
customer     1000
orderdate    1000
product      1000
units        1000
unitprice    1000
dtype: int64

# 05. Data Analysis: Preliminar Analysis

In [48]:
import pandas as pd

In [49]:
data = pd.read_csv('./data/titanic/titanic3.csv')

In [51]:
data.head(10)

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   
5       1         1                              Anderson, Mr. Harry    male   
6       1         1                Andrews, Miss. Kornelia Theodosia  female   
7       1         0                           Andrews, Mr. Thomas Jr    male   
8       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)  female   
9       1         0                          Artagaveytia, Mr. Ramon    male   

       age  sibsp  parch    ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0     24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2    113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2    113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2    113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2    113781  151.5500  C22 C26        S  NaN    NaN   
5  48.0000      0      0     19952   26.5500      E12        S    3    NaN   
6  63.0000      1      0     13502   77.9583       D7        S   10    NaN   
7  39.0000      0      0    112050    0.0000      A36        S  NaN    NaN   
8  53.0000      2      0     11769   51.4792     C101        S    D    NaN   
9  71.0000      0      0  PC 17609   49.5042      NaN        C  NaN   22.0   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON  
5                     New York, NY  
6                       Hudson, NY  
7                      Belfast, NI  
8              Bayside, Queens, NY  
9              Montevideo, Uruguay