# Notes (01–...)

In [1]:
import numpy as np

# 01. What is Numpy

In [2]:
age = [10, 18, 61, 52, 13]

In [3]:
ex_array = np.array(age)

In [4]:
ex_array

array([10, 18, 61, 52, 13])

In [5]:
print(type(ex_array))
print(type(age))

<class 'numpy.ndarray'>
<class 'list'>


In [6]:
ex_array_1 = np.array([10, 18, 61, 52, 13])
ex_array_1

array([10, 18, 61, 52, 13])

In [7]:
ex_array_2 = np.array([[10, 17, 13], [61, 52, 43]])
ex_array_2

array([[10, 17, 13],
       [61, 52, 43]])

In [8]:
print(np.shape(ex_array_1))
print(np.shape(ex_array_2))

(5,)
(2, 3)


In [9]:
print(ex_array_1.shape)
print(ex_array_2.shape)

(5,)
(2, 3)


In [10]:
ex_array_1.shape, ex_array_2.shape

((5,), (2, 3))

In [11]:
print(ex_array_1.size)
print(ex_array_2.size)

5
6


In [12]:
print(ex_array_1.itemsize)
print(ex_array_2.itemsize)

4
4


In [13]:
print(ex_array_1.nbytes)
print(ex_array_2.nbytes)

20
24


In [14]:
print(ex_array_1.ndim)
print(ex_array_2.ndim)

1
2


In [15]:
age_tuple = (10, 18, 61, 52, 13)

In [16]:
ex_array_1_tuple = np.array(age_tuple)
ex_array_1_tuple

array([10, 18, 61, 52, 13])

In [17]:
ex_array_1_func = np.arange(1, 100+1, 1)
print(ex_array_1_func)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [18]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is Fals

In [19]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [20]:
np.logspace?

Signature:
np.logspace(
    start,
    stop,
    num=50,
    endpoint=True,
    base=10.0,
    dtype=None,
    axis=0,
)
Docstring:
Return numbers spaced evenly on a log scale.

In linear space, the sequence starts at ``base ** start``
(`base` to the power of `start`) and ends with ``base ** stop``
(see `endpoint` below).

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    ``base ** start`` is the starting value of the sequence.
stop : array_like
    ``base ** stop`` is the final value of the sequence, unless `endpoint`
    is False.  In that case, ``num + 1`` values are spaced over the
    interval in log-space, of which all but the last (a sequence of
    length `num`) are returned.
num : integer, optional
    Number of samples to generate.  Default is 50.
endpoint : boolean, optional
    If true, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
base : array_like, optional
    The

In [21]:
np.logspace(1, 16, 2)

array([1.e+01, 1.e+16])

In [22]:
np.e

2.718281828459045

In [23]:
np.e**2

7.3890560989306495

In [24]:
np.logspace(
    0,         # start  starting value of the sequence
    np.e**2,   # stop   ending value of the sequence
    10,        # num    number of elements in the sequence
    base=np.e  # base   base of the logarithm
)

array([1.00000000e+00, 2.27278564e+00, 5.16555456e+00, 1.17401982e+01,
       2.66829540e+01, 6.06446346e+01, 1.37832255e+02, 3.13263169e+02,
       7.11980032e+02, 1.61817799e+03])

In [25]:
np.logspace(
    1,
    16,
    5,
    2
)

array([1.00000000e+01, 5.62341325e+04, 3.16227766e+08, 1.77827941e+12,
       1.00000000e+16])

In [26]:
np.mgrid?

Type:        MGridClass
String form: <numpy.lib.index_tricks.MGridClass object at 0x000002CDB641D790>
File:        c:\programdata\anaconda3\lib\site-packages\numpy\lib\index_tricks.py
Docstring:  
`nd_grid` instance which returns a dense multi-dimensional "meshgrid".

An instance of `numpy.lib.index_tricks.nd_grid` which returns an dense
(or fleshed out) mesh-grid when indexed, so that each returned argument
has the same shape.  The dimensions and number of the output arrays are
equal to the number of indexing dimensions.  If the step length is not a
complex number, then the stop is not inclusive.

However, if the step length is a **complex number** (e.g. 5j), then
the integer part of its magnitude is interpreted as specifying the
number of points to create between the start and stop values, where
the stop value **is inclusive**.

Returns
-------
mesh-grid `ndarrays` all of the same dimensions

See Also
--------
numpy.lib.index_tricks.nd_grid : class of `ogrid` and `mgrid` objects
ogri

In [27]:
ex_grid = np.mgrid[0:5, 0:5]
ex_grid

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [28]:
ex_grid[1, 2, 3]

3

In [29]:
np.mgrid[0:1+1, 0:1+1]

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [35]:
np.random.randn(1, 1)

array([[-1.60071163]])

In [34]:
np.random.randn(2, 2)

array([[ 0.38512272, -1.11140363],
       [ 0.61842158,  0.24285243]])

In [32]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the ``standard_normal`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python

In [100]:
np.random.seed(4)

In [133]:
r = np.random.rand(10, 2)

In [141]:
r

array([[0.08305444, 0.23964044],
       [0.22148276, 0.3635998 ],
       [0.81031423, 0.06009617],
       [0.44974356, 0.81317053],
       [0.26423837, 0.06340098],
       [0.24210767, 0.08507046],
       [0.80777744, 0.17025008],
       [0.19534463, 0.81464201],
       [0.81028553, 0.58937388],
       [0.91473434, 0.05982164]])

In [107]:
np.random.seed(5)

In [108]:
r2 = np.random.rand(5,5)

In [117]:
r2

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
       [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123],
       [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703],
       [0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781],
       [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395]])

In [113]:
r2

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
       [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123],
       [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703],
       [0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781],
       [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395]])

In [142]:
r3 = np.random.rand(10, 2)

In [145]:
r3

array([[0.96499664, 0.57097522],
       [0.30251811, 0.82570583],
       [0.65941728, 0.98650144],
       [0.10748953, 0.58091853],
       [0.47282816, 0.65227079],
       [0.24185905, 0.03113006],
       [0.54423235, 0.36471018],
       [0.89233328, 0.45934559],
       [0.4186541 , 0.63290554],
       [0.52717883, 0.96121114]])

In [234]:
np.random.seed(1231)
random_number = np.random.rand(5)
random_number

array([0.4349867 , 0.97345204, 0.62407665, 0.34092971, 0.69136453])

In [216]:
random_numbers = np.random.rand(5)
print(random_numbers)

[0.18902576 0.47262131 0.39278117 0.61892993 0.43676629]


In [324]:
np.random.seed(1)
random_with_seed = np.random.rand(2, 2)
random_with_seed

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01]])

In [314]:
random_without_seed = np.random.rand(2, 5)
random_without_seed

array([[0.57019677, 0.43860151, 0.98837384, 0.10204481, 0.20887676],
       [0.16130952, 0.65310833, 0.2532916 , 0.46631077, 0.24442559]])

In [330]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [340]:
np.diag([1, 2, 3, 4], k=-1)[::-1]

array([[0, 0, 0, 4, 0],
       [0, 0, 3, 0, 0],
       [0, 2, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [347]:
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [352]:
np.zeros((5, 2), dtype='int')

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [354]:
np.ones((5, 3), dtype='int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [355]:
np.empty((4, 2), dtype='str')

array([['', ''],
       ['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [359]:
np.empty((4, 2))

array([[0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 7.70742408e-321],
       [1.08221785e-312, 8.70018274e-313]])

In [360]:
np.full((4, 2), '', dtype='str')

array([['', ''],
       ['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [363]:
np.diag(np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [375]:
ex_array = np.array([[6, 7], [8, 9]])
print(ex_array)

[[6 7]
 [8 9]]


In [376]:
np.tile(ex_array, (3, 2))

array([[6, 7, 6, 7],
       [8, 9, 8, 9],
       [6, 7, 6, 7],
       [8, 9, 8, 9],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

In [378]:
L = range(100_000)
L

range(0, 100000)

In [381]:
upgraded_b = [i**3 for i in range(1, 4+1)]
upgraded_b

[1, 8, 27, 64]

In [384]:
L = range(10)
new_L = [i**2 for i in L]
new_L

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]