# Notes (03)

In [1]:
import numpy as np
# from scipy import sparse
from scipy.sparse import lil_matrix, csr_matrix

In [2]:
try: 
    import plmb
except ImportError:
    !pip install pmlb

# 03. Datasets and Benchmark

In [3]:
import pmlb

In [4]:
pmlb.dataset_names

['GAMETES_Epistasis_2_Way_1000atts_0.4H_EDM_1_EDM_1_1',
 'GAMETES_Epistasis_2_Way_20atts_0.1H_EDM_1_1',
 'GAMETES_Epistasis_2_Way_20atts_0.4H_EDM_1_1',
 'GAMETES_Epistasis_3_Way_20atts_0.2H_EDM_1_1',
 'GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_50_EDM_2_001',
 'GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_75_EDM_2_001',
 'Hill_Valley_with_noise',
 'Hill_Valley_without_noise',
 'adult',
 'agaricus_lepiota',
 'allbp',
 'allhyper',
 'allhypo',
 'allrep',
 'analcatdata_aids',
 'analcatdata_asbestos',
 'analcatdata_authorship',
 'analcatdata_bankruptcy',
 'analcatdata_boxing1',
 'analcatdata_boxing2',
 'analcatdata_creditscore',
 'analcatdata_cyyoung8092',
 'analcatdata_cyyoung9302',
 'analcatdata_dmft',
 'analcatdata_fraud',
 'analcatdata_germangss',
 'analcatdata_happiness',
 'analcatdata_japansolvent',
 'analcatdata_lawsuit',
 'ann_thyroid',
 'appendicitis',
 'australian',
 'auto',
 'backache',
 'balance_scale',
 'biomed',
 'breast',
 'breast_cancer',
 'breast_cancer_wisconsin',
 'br

In [5]:
print('All datasets in PMLB:')
print('—————————————————————')
print('\n')

for i, set in enumerate(pmlb.dataset_names):
    print(f'{i+1}. {set}')

All datasets in PMLB:
—————————————————————


1. GAMETES_Epistasis_2_Way_1000atts_0.4H_EDM_1_EDM_1_1
2. GAMETES_Epistasis_2_Way_20atts_0.1H_EDM_1_1
3. GAMETES_Epistasis_2_Way_20atts_0.4H_EDM_1_1
4. GAMETES_Epistasis_3_Way_20atts_0.2H_EDM_1_1
5. GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_50_EDM_2_001
6. GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_75_EDM_2_001
7. Hill_Valley_with_noise
8. Hill_Valley_without_noise
9. adult
10. agaricus_lepiota
11. allbp
12. allhyper
13. allhypo
14. allrep
15. analcatdata_aids
16. analcatdata_asbestos
17. analcatdata_authorship
18. analcatdata_bankruptcy
19. analcatdata_boxing1
20. analcatdata_boxing2
21. analcatdata_creditscore
22. analcatdata_cyyoung8092
23. analcatdata_cyyoung9302
24. analcatdata_dmft
25. analcatdata_fraud
26. analcatdata_germangss
27. analcatdata_happiness
28. analcatdata_japansolvent
29. analcatdata_lawsuit
30. ann_thyroid
31. appendicitis
32. australian
33. auto
34. backache
35. balance_scale
36. biomed
37. breast
38. breast_ca

In [6]:
from pmlb import fetch_data

In [15]:
banana = fetch_data('banana')

In [14]:
banana.head()

At1    At2  target
0  1.140 -0.114       0
1 -1.520 -1.150       1
2 -1.050  0.720       0
3 -0.916  0.397       1
4 -1.090  0.437       1

In [11]:
adult = fetch_data('adult')

In [17]:
adult.head(20)

age  workclass    fnlwgt  education  education-num  marital-status  \
0   39.0          7   77516.0          9           13.0               4   
1   50.0          6   83311.0          9           13.0               2   
2   38.0          4  215646.0         11            9.0               0   
3   53.0          4  234721.0          1            7.0               2   
4   28.0          4  338409.0          9           13.0               2   
5   37.0          4  284582.0         12           14.0               2   
6   49.0          4  160187.0          6            5.0               3   
7   52.0          6  209642.0         11            9.0               2   
8   31.0          4   45781.0         12           14.0               4   
9   42.0          4  159449.0          9           13.0               2   
10  37.0          4  280464.0         15           10.0               2   
11  30.0          7  141297.0          9           13.0               2   
12  23.0          4  122272.0          9           13.0               4   
13  32.0          4  205019.0          7           12.0               4   
14  40.0          4  121772.0          8           11.0               2   
15  34.0          4  245487.0          5            4.0               2   
16  25.0          6  176756.0         11            9.0               4   
17  32.0          4  186824.0         11            9.0               4   
18  38.0          4   28887.0          1            7.0               2   
19  43.0          6  292175.0         12           14.0               0   

    occupation  relationship  race  sex  capital-gain  capital-loss  \
0            1             1     4    1        2174.0           0.0   
1            4             0     4    1           0.0           0.0   
2            6             1     4    1           0.0           0.0   
3            6             0     2    1           0.0           0.0   
4           10             5     2    0           0.0           0.0   
5            4             5     4    0           0.0           0.0   
6            8             1     2    0           0.0           0.0   
7            4             0     4    1           0.0           0.0   
8           10             1     4    0       14084.0           0.0   
9            4             0     4    1        5178.0           0.0   
10           4             0     2    1           0.0           0.0   
11          10             0     1    1           0.0           0.0   
12           1             3     4    0           0.0           0.0   
13          12             1     2    1           0.0           0.0   
14           3             0     1    1           0.0           0.0   
15          14             0     0    1           0.0           0.0   
16           5             3     4    1           0.0           0.0   
17           7             4     4    1           0.0           0.0   
18          12             0     4    1           0.0           0.0   
19           4             4     4    0           0.0           0.0   

    hours-per-week  native-country  target  
0             40.0              39       1  
1             13.0              39       1  
2             40.0              39       1  
3             40.0              39       1  
4             40.0               5       1  
5             40.0              39       1  
6             16.0              23       1  
7             45.0              39       0  
8             50.0              39       0  
9             40.0              39       0  
10            80.0              39       0  
11            40.0              19       0  
12            30.0              39       1  
13            50.0              39       1  
14            40.0               0       0  
15            45.0              26       1  
16            35.0              39       1  
17            40.0              39       1  
18            50.0              39       1  
19            45.0              39   

In [19]:
adult

age  workclass    fnlwgt  education  education-num  marital-status  \
0      39.0          7   77516.0          9           13.0               4   
1      50.0          6   83311.0          9           13.0               2   
2      38.0          4  215646.0         11            9.0               0   
3      53.0          4  234721.0          1            7.0               2   
4      28.0          4  338409.0          9           13.0               2   
...     ...        ...       ...        ...            ...             ...   
48837  39.0          4  215419.0          9           13.0               0   
48838  64.0          0  321403.0         11            9.0               6   
48839  38.0          4  374983.0          9           13.0               2   
48840  44.0          4   83891.0          9           13.0               0   
48841  35.0          5  182148.0          9           13.0               2   

       occupation  relationship  race  sex  capital-gain  capital-loss  \
0               1             1     4    1        2174.0           0.0   
1               4             0     4    1           0.0           0.0   
2               6             1     4    1           0.0           0.0   
3               6             0     2    1           0.0           0.0   
4              10             5     2    0           0.0           0.0   
...           ...           ...   ...  ...           ...           ...   
48837          10             1     4    0           0.0           0.0   
48838           0             2     2    1           0.0           0.0   
48839          10             0     4    1           0.0           0.0   
48840           1             3     1    1        5455.0           0.0   
48841           4             0     4    1           0.0           0.0   

       hours-per-week  native-country  target  
0                40.0              39       1  
1                13.0              39       1  
2                40.0              39       1  
3                40.0              39       1  
4                40.0               5       1  
...               ...             ...     ...  
48837            36.0              39       1  
48838            40.0              39       1  
48839            50.0              39       1  
48840            40.0              39       1  
48841            60.0              39       0  

[48842 rows x 15 columns]

In [20]:
banana_X, banana_y = fetch_data('banana', return_X_y=True)

print(banana_X, '\n')
print(banana_y)

[[ 1.14  -0.114]
 [-1.52  -1.15 ]
 [-1.05   0.72 ]
 ...
 [ 2.64   1.14 ]
 [ 0.769  0.772]
 [-0.255 -0.142]] 

[0 1 0 ... 1 0 1]


In [21]:
banana_X, banana_y = fetch_data('banana', return_X_y=True, local_cache_dir='./data')

print(banana_X, '\n')
print(banana_y)

[[ 1.14  -0.114]
 [-1.52  -1.15 ]
 [-1.05   0.72 ]
 ...
 [ 2.64   1.14 ]
 [ 0.769  0.772]
 [-0.255 -0.142]] 

[0 1 0 ... 1 0 1]


In [25]:
bc_1 = fetch_data('breast_cancer', local_cache_dir='./data')
bc_1.head(30)

age  menopause  tumor-size  inv-nodes  node-caps  deg-malig  breast  \
0     2          2           2          0          2          3       1   
1     3          0           2          0          1          1       1   
2     3          0           6          0          1          2       0   
3     2          2           6          0          2          3       1   
4     2          2           5          4          2          2       0   
5     3          2           4          4          1          2       1   
6     3          0           7          0          1          3       0   
7     2          2           1          0          1          2       0   
8     2          2           0          0          1          2       1   
9     2          0           7          2          2          2       1   
10    3          2           4          0          1          2       0   
11    4          0           2          0          1          2       1   
12    3          0           5          0          1          1       1   
13    3          0           4          0          1          2       1   
14    2          2           4          0          1          2       0   
15    1          2           3          0          1          3       0   
16    3          2           1          4          1          1       1   
17    4          0           2          0          1          2       1   
18    3          2           7          0          1          2       0   
19    3          0           3          0          1          3       0   
20    3          1           3          0          0          1       0   
21    4          0           7          4          1          2       1   
22    3          0           2          0          1          2       1   
23    2          2           1          0          1          1       1   
24    1          2           2          5          2          3       0   
25    3          0           3          4          2          2       1   
26    3          0           1          0          1          2       1   
27    2          2           1          0          1          1       1   
28    4          0           5          4          2          3       0   
29    2          2           2          2          2          3       0   

    breast-quad  irradiat  target  
0             3         0       1  
1             1         0       0  
2             2         0       1  
3             2         1       0  
4             5         0       1  
5             3         1       0  
6             3         0       0  
7             3         0       0  
8             4         0       0  
9             3         1       0  
10            2         0       0  
11            3         0       0  
12            1         0       0  
13            3         0       0  
14            2         1       1  
15            1         0       0  
16            3         0       0  
17            3         0       0  
18            3         0       0  
19            3         0       0  
20            2         0       1  
21            3         1       0  
22            2         0       0  
23            3         0       0  
24            2         1       1  
25            3         0       0  
26            2         0       0  
27            3         0       0  
28            2         0       0  
29            2         0       1

In [27]:
bc_2 = fetch_data('breast_cancer', local_cache_dir='')
bc_2.head(30)

age  menopause  tumor-size  inv-nodes  node-caps  deg-malig  breast  \
0     2          2           2          0          2          3       1   
1     3          0           2          0          1          1       1   
2     3          0           6          0          1          2       0   
3     2          2           6          0          2          3       1   
4     2          2           5          4          2          2       0   
5     3          2           4          4          1          2       1   
6     3          0           7          0          1          3       0   
7     2          2           1          0          1          2       0   
8     2          2           0          0          1          2       1   
9     2          0           7          2          2          2       1   
10    3          2           4          0          1          2       0   
11    4          0           2          0          1          2       1   
12    3          0           5          0          1          1       1   
13    3          0           4          0          1          2       1   
14    2          2           4          0          1          2       0   
15    1          2           3          0          1          3       0   
16    3          2           1          4          1          1       1   
17    4          0           2          0          1          2       1   
18    3          2           7          0          1          2       0   
19    3          0           3          0          1          3       0   
20    3          1           3          0          0          1       0   
21    4          0           7          4          1          2       1   
22    3          0           2          0          1          2       1   
23    2          2           1          0          1          1       1   
24    1          2           2          5          2          3       0   
25    3          0           3          4          2          2       1   
26    3          0           1          0          1          2       1   
27    2          2           1          0          1          1       1   
28    4          0           5          4          2          3       0   
29    2          2           2          2          2          3       0   

    breast-quad  irradiat  target  
0             3         0       1  
1             1         0       0  
2             2         0       1  
3             2         1       0  
4             5         0       1  
5             3         1       0  
6             3         0       0  
7             3         0       0  
8             4         0       0  
9             3         1       0  
10            2         0       0  
11            3         0       0  
12            1         0       0  
13            3         0       0  
14            2         1       1  
15            1         0       0  
16            3         0       0  
17            3         0       0  
18            3         0       0  
19            3         0       0  
20            2         0       1  
21            3         1       0  
22            2         0       0  
23            3         0       0  
24            2         1       1  
25            3         0       0  
26            2         0       0  
27            3         0       0  
28            2         0       0  
29            2         0       1

In [31]:
from pmlb import fetch_data, classification_dataset_names

for i, classification_dataset in enumerate(classification_dataset_names):
    print(i, classification_dataset)

0 GAMETES_Epistasis_2_Way_1000atts_0.4H_EDM_1_EDM_1_1
1 GAMETES_Epistasis_2_Way_20atts_0.1H_EDM_1_1
2 GAMETES_Epistasis_2_Way_20atts_0.4H_EDM_1_1
3 GAMETES_Epistasis_3_Way_20atts_0.2H_EDM_1_1
4 GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_50_EDM_2_001
5 GAMETES_Heterogeneity_20atts_1600_Het_0.4_0.2_75_EDM_2_001
6 Hill_Valley_with_noise
7 Hill_Valley_without_noise
8 adult
9 agaricus_lepiota
10 allbp
11 allhyper
12 allhypo
13 allrep
14 analcatdata_aids
15 analcatdata_asbestos
16 analcatdata_authorship
17 analcatdata_bankruptcy
18 analcatdata_boxing1
19 analcatdata_boxing2
20 analcatdata_creditscore
21 analcatdata_cyyoung8092
22 analcatdata_cyyoung9302
23 analcatdata_dmft
24 analcatdata_fraud
25 analcatdata_germangss
26 analcatdata_happiness
27 analcatdata_japansolvent
28 analcatdata_lawsuit
29 ann_thyroid
30 appendicitis
31 australian
32 auto
33 backache
34 balance_scale
35 biomed
36 breast
37 breast_cancer
38 breast_cancer_wisconsin
39 breast_w
40 buggyCrx
41 bupa
42 calendarDOW
43 car

In [32]:
analcatdata_creditscore = fetch_data('analcatdata_creditscore')
analcatdata_creditscore

Age  Income.per.dependent  Monthly.credit.card.exp  Own.home  \
0   38.0                  4.52                   124.98         1   
1   33.0                  2.42                     9.85         0   
2   34.0                  4.50                    15.00         1   
3   31.0                  2.54                   137.87         0   
4   32.0                  9.79                   546.50         1   
..   ...                   ...                      ...       ...   
95  22.0                  1.56                     0.00         0   
96  33.0                  6.00                   474.15         1   
97  25.0                  3.60                   234.05         0   
98  26.0                  5.00                   451.20         1   
99  46.0                  5.50                   251.52         1   

    Self.employed  Derogatory.reports  target  
0               0                   0       1  
1               0                   0       1  
2               0                   0       1  
3               0                   0       1  
4               0                   0       1  
..            ...                 ...     ...  
95              0                   0       1  
96              0                   1       1  
97              0                   1       1  
98              0                   0       1  
99              0                   0       1  

[100 rows x 7 columns]