# Notes (02)

In [1]:
import numpy as np
from scipy import sparse

# 02. Representation of Data (for Machine Learning)

In [2]:
np.random.seed(42)
X = np.random.random((10, 5))
X[X < 0.7] = 0
print(X)

[[0.         0.95071431 0.73199394 0.         0.        ]
 [0.         0.         0.86617615 0.         0.70807258]
 [0.         0.96990985 0.83244264 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.78517596 0.         0.         0.         0.        ]
 [0.         0.         0.         0.94888554 0.96563203]
 [0.80839735 0.         0.         0.         0.        ]
 [0.         0.         0.         0.9093204  0.        ]
 [0.         0.         0.         0.         0.        ]]


In [3]:
print(X)

[[0.         0.95071431 0.73199394 0.         0.        ]
 [0.         0.         0.86617615 0.         0.70807258]
 [0.         0.96990985 0.83244264 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.78517596 0.         0.         0.         0.        ]
 [0.         0.         0.         0.94888554 0.96563203]
 [0.80839735 0.         0.         0.         0.        ]
 [0.         0.         0.         0.9093204  0.        ]
 [0.         0.         0.         0.         0.        ]]


In [4]:
X_csr = sparse.csr_matrix(X)
print(X_csr)

  (0, 1)	0.9507143064099162
  (0, 2)	0.7319939418114051
  (1, 2)	0.8661761457749352
  (1, 4)	0.7080725777960455
  (2, 1)	0.9699098521619943
  (2, 2)	0.8324426408004217
  (5, 0)	0.7851759613930136
  (6, 3)	0.9488855372533332
  (6, 4)	0.9656320330745594
  (7, 0)	0.8083973481164611
  (8, 3)	0.9093204020787821


In [5]:
print(X_csr.toarray())

[[0.         0.95071431 0.73199394 0.         0.        ]
 [0.         0.         0.86617615 0.         0.70807258]
 [0.         0.96990985 0.83244264 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.78517596 0.         0.         0.         0.        ]
 [0.         0.         0.         0.94888554 0.96563203]
 [0.80839735 0.         0.         0.         0.        ]
 [0.         0.         0.         0.9093204  0.        ]
 [0.         0.         0.         0.         0.        ]]


In [6]:
print(X_csr.shape[1])

5


In [7]:
y = np.random.random(5)
y

array([0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998])

In [8]:
print(X_csr)

  (0, 1)	0.9507143064099162
  (0, 2)	0.7319939418114051
  (1, 2)	0.8661761457749352
  (1, 4)	0.7080725777960455
  (2, 1)	0.9699098521619943
  (2, 2)	0.8324426408004217
  (5, 0)	0.7851759613930136
  (6, 3)	0.9488855372533332
  (6, 4)	0.9656320330745594
  (7, 0)	0.8083973481164611
  (8, 3)	0.9093204020787821


In [9]:
z1 = X_csr.dot(y)
z1

array([1.4246374 , 1.23712815, 1.53388794, 0.        , 0.        ,
       0.76129454, 1.4264401 , 0.78380964, 0.81368477, 0.        ])

In [10]:
X

array([[0.        , 0.95071431, 0.73199394, 0.        , 0.        ],
       [0.        , 0.        , 0.86617615, 0.        , 0.70807258],
       [0.        , 0.96990985, 0.83244264, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.78517596, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.94888554, 0.96563203],
       [0.80839735, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.9093204 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [11]:
z2 = X.dot(y)
z2

array([1.4246374 , 1.23712815, 1.53388794, 0.        , 0.        ,
       0.76129454, 1.4264401 , 0.78380964, 0.81368477, 0.        ])

In [12]:
example_1 = np.arange(0, 5)
example_2 = np.arange(0, 5)
example_3 = np.arange(0+10, 5+10)

np.allclose(example_1, example_2)

True

In [13]:
np.allclose(example_2, example_3)

False

In [14]:
array_1 = np.arange(0, 5)
array_1

array([0, 1, 2, 3, 4])

In [15]:
array_2 = np.arange(0+5, 5+5)
array_2

array([5, 6, 7, 8, 9])

In [16]:
dot_product = array_1.dot(array_2)
dot_product

80

In [17]:
print(sparse.lil_matrix((5,5)))

In [18]:
def find_max_element(numbers):
    max_element = float("-inf")  # Initialize to negative infinity
    for num in numbers:
        if num > max_element:
            max_element = num
    return max_element

# Example usage:
numbers_list = [5, 9, 2, 15, 7]
max_num = find_max_element(numbers_list)
print("Maximum element:", max_num) 

Maximum element: 15


In [19]:
def find_max_element_2(numbers):
    max_element = 0
    for num in numbers:
        if num > max_element:
            max_element = num
    return max_element

In [20]:
numbers_list = [0, 2, 3, 64, 23, 3, 42, 5, 9]

In [21]:
max_num_2 = find_max_element_2(numbers_list)
max_num_2

64

In [22]:
def min_element(num_list):
    lowest_value = float('inf')
    
    for n in num_list:
        if n < lowest_value:
            lowest_value = n
    return lowest_value

In [23]:
numbers_list = [0.05, 12, 42, 12, 0.001, 0.312, -0.3234, -0.031, -120, 231, 21]

In [24]:
min_element(numbers_list)

-120

In [25]:
a193628 = np.random.randint(0, 5, (15, 2))
print(a193628)

[[3 0]
 [4 4]
 [1 4]
 [1 0]
 [3 3]
 [3 4]
 [0 4]
 [4 0]
 [0 0]
 [0 3]
 [2 2]
 [0 2]
 [2 0]
 [2 4]
 [1 1]]


In [26]:
a193628[1, 0]

4

In [27]:
X_lil = sparse.lil_matrix((5, 5))
X_lil

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in List of Lists format>

In [28]:
for i, j in a193628:
    X_lil[i, j] = i + j
    
print(X_lil.toarray(), '\n')
print(X_lil)

[[0. 0. 2. 3. 4.]
 [1. 2. 0. 0. 5.]
 [2. 0. 4. 0. 6.]
 [3. 0. 0. 6. 7.]
 [4. 0. 0. 0. 8.]] 

  (0, 2)	2.0
  (0, 3)	3.0
  (0, 4)	4.0
  (1, 0)	1.0
  (1, 1)	2.0
  (1, 4)	5.0
  (2, 0)	2.0
  (2, 2)	4.0
  (2, 4)	6.0
  (3, 0)	3.0
  (3, 3)	6.0
  (3, 4)	7.0
  (4, 0)	4.0
  (4, 4)	8.0


In [29]:
for i, j in a193628:
    print(i, j)

3 0
4 4
1 4
1 0
3 3
3 4
0 4
4 0
0 0
0 3
2 2
0 2
2 0
2 4
1 1


In [30]:
a193628

array([[3, 0],
       [4, 4],
       [1, 4],
       [1, 0],
       [3, 3],
       [3, 4],
       [0, 4],
       [4, 0],
       [0, 0],
       [0, 3],
       [2, 2],
       [0, 2],
       [2, 0],
       [2, 4],
       [1, 1]])

In [31]:
a200528 = np.random.randint(0, 2, (5, 2))
print(a200528)

[[0 1]
 [0 0]
 [1 1]
 [1 0]
 [1 0]]


In [32]:
X_lil_2 = sparse.lil_matrix((3, 3))

for r, c in a200528:
    X_lil_2[r, c] = r + c
    
print(X_lil_2, '\n')
print(X_lil_2.toarray())

  (0, 1)	1.0
  (1, 0)	1.0
  (1, 1)	2.0 

[[0. 1. 0.]
 [1. 2. 0.]
 [0. 0. 0.]]


In [33]:
X_lil_2

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in List of Lists format>

In [34]:
X_csr = X_lil_2.tocsr()
X_csr

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [35]:
print(X_csr)

  (0, 1)	1.0
  (1, 0)	1.0
  (1, 1)	2.0


In [36]:
X_lil_2

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in List of Lists format>

In [37]:
print(X_lil_2)

  (0, 1)	1.0
  (1, 0)	1.0
  (1, 1)	2.0


In [38]:
X_csc = X_lil_2.tocsc()
X_csc

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Column format>

In [39]:
print(X_csc)

  (1, 0)	1.0
  (0, 1)	1.0
  (1, 1)	2.0


In [42]:
A1 = np.array([0, 2, 3, 6])
print(A1)

[0 2 3 6]


In [43]:
A2 = np.array([0, 2, 2, 0, 1, 2])
print(A2)

[0 2 2 0 1 2]


In [44]:
A3 = np.array([1, 2, 3, 4, 5, 6]).repeat(4)
print(A3)

[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6]


In [46]:
A4 = np.arange(1, 7).repeat(4)
print(A4)

[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6]


In [52]:
EX1 = np.arange(0, 5)
print(EX1)

[0 1 2 3 4]


In [55]:
EX2 = EX1.repeat(4)    # or np.arange(0, 5).repeat(4)
print(EX2)

[0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4]


In [56]:
A5 = A4.reshape(6, 2, 2)
print(A5)

[[[1 1]
  [1 1]]

 [[2 2]
  [2 2]]

 [[3 3]
  [3 3]]

 [[4 4]
  [4 4]]

 [[5 5]
  [5 5]]

 [[6 6]
  [6 6]]]


In [60]:
array1 = np.array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6])
print(array1)

[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6]


In [61]:
array2 = array1.reshape(6, 2, 2)
print(array2)

[[[1 1]
  [1 1]]

 [[2 2]
  [2 2]]

 [[3 3]
  [3 3]]

 [[4 4]
  [4 4]]

 [[5 5]
  [5 5]]

 [[6 6]
  [6 6]]]


In [68]:
from scipy.sparse import bsr_matrix

In [69]:
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
indices = [0, 1, 0, 1, 0, 1]
indptr = [0, 2, 4, 6]

In [83]:
from scipy.sparse import bsr_matrix
import numpy as np

# Create the 2x2 blocks
block1 = np.array([[1, 2], [3, 4]])
block2 = np.array([[5, 6], [7, 8]])
block3 = np.array([[9, 10], [11, 12]])

# Stack the blocks to create the data array
data = np.array([block1, block2, block3])

# Define the column indices of the blocks
indices = np.array([0, 0, 0])

# Define the row pointers to the blocks
indptr = np.array([0, 0, 0, 0])  # Adjusted indptr to be of size 4

# Create the BSR matrix
bsr_matrix((data, indices, indptr), shape=(6, 6)).toarray()

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [78]:
data

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [87]:
ones = np.ones((2, 3), dtype=int)
data = np.array([ones + i for i in range(4)])
data

array([[[1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2]],

       [[3, 3, 3],
        [3, 3, 3]],

       [[4, 4, 4],
        [4, 4, 4]]])

In [94]:
from scipy.sparse import bsr_matrix

indptr = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6]).repeat(4).reshape(6, 2, 2)
bsr_matrix((data, indices, indptr), shape = (6, 6)).toarray()

array([[1, 1, 0, 0, 2, 2],
       [1, 1, 0, 0, 2, 2],
       [0, 0, 0, 0, 3, 3],
       [0, 0, 0, 0, 3, 3],
       [4, 4, 5, 5, 6, 6],
       [4, 4, 5, 5, 6, 6]])

In [96]:
data = np.array([1, 2, 3, 4, 5, 6]).repeat(4).reshape(6, 2, 2)
print(data)

[[[1 1]
  [1 1]]

 [[2 2]
  [2 2]]

 [[3 3]
  [3 3]]

 [[4 4]
  [4 4]]

 [[5 5]
  [5 5]]

 [[6 6]
  [6 6]]]


In [99]:
from scipy.sparse import bsr_matrix

indptr = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6]).repeat(4).reshape(6, 2, 2)

print(bsr_matrix((data, indices, indptr), shape = (6, 6)).toarray())

[[1 1 0 0 2 2]
 [1 1 0 0 2 2]
 [0 0 0 0 3 3]
 [0 0 0 0 3 3]
 [4 4 5 5 6 6]
 [4 4 5 5 6 6]]


In [110]:
print(data[0], '\n')
print(data[2], '\n')
print(data[2], '\n')
print(data[0], '\n')
print(data[1], '\n')
print(data[2])

[[1 1]
 [1 1]] 

[[3 3]
 [3 3]] 

[[3 3]
 [3 3]] 

[[1 1]
 [1 1]] 

[[2 2]
 [2 2]] 

[[3 3]
 [3 3]]


In [100]:
from scipy.sparse import bsr_matrix
import numpy as np

# Create the 2x2 blocks
block1 = np.array([[1, 1], [1, 1]])
block2 = np.array([[2, 2], [2, 2]])
block3 = np.array([[3, 3], [3, 3]])
block4 = np.array([[4, 4], [4, 4]])
block5 = np.array([[5, 5], [5, 5]])
block6 = np.array([[6, 6], [6, 6]])

# Stack the blocks to create the data array
data = np.array([block1, block2, block3, block4, block5, block6])

# Define the column indices of the blocks
indices = np.array([0, 2, 2, 0, 1, 2])

# Define the row pointers to the blocks
indptr = np.array([0, 2, 3, 6])

# Create the BSR matrix
bsr_matrix((data, indices, indptr), shape=(6, 6)).toarray()

array([[1, 1, 0, 0, 2, 2],
       [1, 1, 0, 0, 2, 2],
       [0, 0, 0, 0, 3, 3],
       [0, 0, 0, 0, 3, 3],
       [4, 4, 5, 5, 6, 6],
       [4, 4, 5, 5, 6, 6]])

In [112]:
row = [1, 3, 0, 2, 4]
col = [1, 4, 2, 3, 3]
data = [2, 5, 9, 1, 6]
coo = sparse.coo_matrix((data, (row, col)), shape=(6, 7))
print(coo)
coo.toarray()

  (1, 1)	2
  (3, 4)	5
  (0, 2)	9
  (2, 3)	1
  (4, 3)	6


array([[0, 0, 9, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [119]:
row = [1, 3, 0, 2, 4]
col = [1, 4, 2, 3, 3]
data = [2, 5, 9, 1, 6]

coo = sparse.coo_matrix((data, (row, col)), shape=(6, 7))

print(coo, '\n')
print(coo.toarray())

  (1, 1)	2
  (3, 4)	5
  (0, 2)	9
  (2, 3)	1
  (4, 3)	6 

[[0 0 9 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0]]


In [120]:
coo.tocsr()

<6x7 sparse matrix of type '<class 'numpy.intc'>'
	with 5 stored elements in Compressed Sparse Row format>

In [121]:
coo

<6x7 sparse matrix of type '<class 'numpy.int32'>'
	with 5 stored elements in COOrdinate format>

In [135]:
from scipy.sparse import dok_matrix

S = dok_matrix((5, 5), dtype=np.float32)

for i in range(5):
    for j in range(i, 5):
        S[i, j] = i+j
        
print(S.toarray())

[[0. 1. 2. 3. 4.]
 [0. 2. 3. 4. 5.]
 [0. 0. 4. 5. 6.]
 [0. 0. 0. 6. 7.]
 [0. 0. 0. 0. 8.]]


In [128]:
ex2030 = dok_matrix((5, 5), dtype=np.float32)

for a in range(5):
    for b in range(a, 5):
        ex2030[a, b] = a + b        

In [129]:
for a in range(5):
    for b in range(5):
        print(a, b)

0 0
0 1
0 2
0 3
0 4
1 0
1 1
1 2
1 3
1 4
2 0
2 1
2 2
2 3
2 4
3 0
3 1
3 2
3 3
3 4
4 0
4 1
4 2
4 3
4 4


In [134]:
range(4, 5)[0]

4

In [136]:
import numpy as np
from scipy.sparse import dok_matrix

# Create a big numpy dense matrix filled with random numbers in [0, 1)
rows, cols = 1000, 1000
dense_matrix = np.random.random((rows, cols))

# Generate a random number within the range [0, 1)
random_number = np.random.random()

# Substitute all elements in the matrix less than the random number with zero
dense_matrix[dense_matrix < random_number] = 0

# Convert the dense matrix to DOK sparse matrix
dok_sparse_matrix = dok_matrix(dense_matrix)

# Print the resulting DOK sparse matrix
print(dok_sparse_matrix)

  (0, 1)	0.32518332202674705
  (0, 2)	0.7296061783380641
  (0, 3)	0.6375574713552131
  (0, 4)	0.8872127425763265
  (0, 5)	0.4722149251619493
  (0, 7)	0.713244787222995
  (0, 8)	0.7607850486168974
  (0, 9)	0.5612771975694962
  (0, 10)	0.770967179954561
  (0, 11)	0.49379559636439074
  (0, 12)	0.5227328293819941
  (0, 13)	0.42754101835854963
  (0, 17)	0.6364104112637804
  (0, 19)	0.5085706911647028
  (0, 20)	0.907566473926093
  (0, 22)	0.41038292303562973
  (0, 23)	0.7555511385430487
  (0, 28)	0.9296976523425731
  (0, 29)	0.808120379564417
  (0, 30)	0.6334037565104235
  (0, 31)	0.8714605901877177
  (0, 32)	0.8036720768991145
  (0, 34)	0.8925589984899778
  (0, 35)	0.5393422419156507
  (0, 36)	0.8074401551640625
  :	:
  (999, 968)	0.33191817185357453
  (999, 970)	0.7894293925253537
  (999, 971)	0.46457328396871256
  (999, 972)	0.4785331973584963
  (999, 974)	0.9686290064312921
  (999, 978)	0.7562896176674918
  (999, 979)	0.9319608885775645
  (999, 980)	0.38916525967580806
  (999, 981)	0.376