# Notes (04–05)

# 04. Introduction

In [1]:
import numpy as np

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)

[1 2 3 4 5]


In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [4]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
arr_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print(arr_4d)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


In [6]:
import pandas as pd

In [7]:
sales_data = pd.read_csv('./data/blooth_sales_data.csv')

In [28]:
pd.set_option('display.max_rows', 9999999999)  # change presets for data preview
sales_data.head(10)

name    birthday                           customer  \
0  Pasquale  1967-09-02                    Electronics Inc   
1     India  1968-12-13         Electronics Resource Group   
2     Wayne  1992-09-10      East Application Contract Inc   
3      Cori  1986-11-05                  Signal Industries   
4     Chang  1972-04-23              Star Alpha Industries   
5    Weldon  1953-03-17             Network Application Co   
6      Sung  1977-10-23  Omega Pacific Future Incorporated   
7     Emily  1982-07-02              Medicine Incorporated   
8   Cornell  1963-07-02     Technology Direct Star Limited   
9     Ervin  1977-10-14                    Provider Agency   

                    orderdate            product  units  unitprice  
0  2016-07-17 13:48:03.156566    Thriller record      2      13.27  
1  2016-07-06 13:48:03.156596            Corolla     26   24458.69  
2  2016-07-22 13:48:03.156618       Rubik’s Cube     41      15.79  
3  2016-07-23 13:48:03.156638             iPhone     16     584.01  
4  2016-07-16 13:48:03.156657  Harry Potter book      4      25.69  
5  2016-07-22 13:48:03.156678            Lipitor      1      11.22  
6  2016-07-09 13:48:03.156698        PlayStation     25     294.90  
7  2016-07-16 13:48:03.156717    Thriller record      5      18.27  
8  2016-07-08 13:48:03.156735       Rubik’s Cube     35      15.98  
9  2016-07-19 13:48:03.156754          Star Wars     24      11.50

In [31]:
sales_data.dtypes

name          object
birthday      object
customer      object
orderdate     object
product       object
units          int64
unitprice    float64
dtype: object

In [39]:
sales_data['birthday'] = pd.to_datetime(sales_data['birthday'])
sales_data.head(5)

name   birthday                       customer  \
0  Pasquale 1967-09-02                Electronics Inc   
1     India 1968-12-13     Electronics Resource Group   
2     Wayne 1992-09-10  East Application Contract Inc   
3      Cori 1986-11-05              Signal Industries   
4     Chang 1972-04-23          Star Alpha Industries   

                    orderdate            product  units  unitprice  
0  2016-07-17 13:48:03.156566    Thriller record      2      13.27  
1  2016-07-06 13:48:03.156596            Corolla     26   24458.69  
2  2016-07-22 13:48:03.156618       Rubik’s Cube     41      15.79  
3  2016-07-23 13:48:03.156638             iPhone     16     584.01  
4  2016-07-16 13:48:03.156657  Harry Potter book      4      25.69

In [40]:
sales_data.dtypes

name                 object
birthday     datetime64[ns]
customer             object
orderdate            object
product              object
units                 int64
unitprice           float64
dtype: object

In [41]:
sales_data['orderdate'] = pd.to_datetime(sales_data['orderdate'])
sales_data.head(5)

name   birthday                       customer  \
0  Pasquale 1967-09-02                Electronics Inc   
1     India 1968-12-13     Electronics Resource Group   
2     Wayne 1992-09-10  East Application Contract Inc   
3      Cori 1986-11-05              Signal Industries   
4     Chang 1972-04-23          Star Alpha Industries   

                   orderdate            product  units  unitprice  
0 2016-07-17 13:48:03.156566    Thriller record      2      13.27  
1 2016-07-06 13:48:03.156596            Corolla     26   24458.69  
2 2016-07-22 13:48:03.156618       Rubik’s Cube     41      15.79  
3 2016-07-23 13:48:03.156638             iPhone     16     584.01  
4 2016-07-16 13:48:03.156657  Harry Potter book      4      25.69

In [42]:
sales_data.dtypes

name                 object
birthday     datetime64[ns]
customer             object
orderdate    datetime64[ns]
product              object
units                 int64
unitprice           float64
dtype: object

In [44]:
# sales_data['birthday', 'orderdate'] = sales_data[['birthday', 'orderdate']].apply(pd.to_datetime)

In [20]:
sales_data.tail()

name    birthday                   customer  \
995     Ethan  1952-12-08     Application Industries   
996   Rudolph  1959-10-15  Network Software West Inc   
997  Annmarie  1982-06-04       Atlantic Corporation   
998     Chang  1984-02-05  Venture Alpha Corporation   
999     Ervin  1977-10-14            Provider Agency   

                      orderdate            product  units  unitprice  
995  2016-07-21 13:48:03.177885  Harry Potter book     39      24.40  
996  2016-07-19 13:48:03.177903       Rubik’s Cube      9      15.11  
997  2016-07-13 13:48:03.177924    Thriller record     19       9.16  
998  2016-07-13 13:48:03.177943  Harry Potter book     24      28.21  
999  2016-07-09 13:48:03.177962             iPhone     39     663.83

In [21]:
len(sales_data)

1000

In [22]:
sales_data.shape

(1000, 7)

In [46]:
sales_data.count()

name         1000
birthday     1000
customer     1000
orderdate    1000
product      1000
units        1000
unitprice    1000
dtype: int64

# 05. Data Analysis: Preliminar Analysis

In [48]:
import pandas as pd

In [49]:
data = pd.read_csv('./data/titanic/titanic3.csv')

In [50]:
data.head(10)

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   
5       1         1                              Anderson, Mr. Harry    male   
6       1         1                Andrews, Miss. Kornelia Theodosia  female   
7       1         0                           Andrews, Mr. Thomas Jr    male   
8       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)  female   
9       1         0                          Artagaveytia, Mr. Ramon    male   

       age  sibsp  parch    ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0     24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2    113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2    113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2    113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2    113781  151.5500  C22 C26        S  NaN    NaN   
5  48.0000      0      0     19952   26.5500      E12        S    3    NaN   
6  63.0000      1      0     13502   77.9583       D7        S   10    NaN   
7  39.0000      0      0    112050    0.0000      A36        S  NaN    NaN   
8  53.0000      2      0     11769   51.4792     C101        S    D    NaN   
9  71.0000      0      0  PC 17609   49.5042      NaN        C  NaN   22.0   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON  
5                     New York, NY  
6                       Hudson, NY  
7                      Belfast, NI  
8              Bayside, Queens, NY  
9              Montevideo, Uruguay

In [16]:
pd.set_option('display.max_rows', 10)

In [17]:
data[:50].isnull()

pclass  survived   name    sex    age  sibsp  parch  ticket   fare  cabin  \
0    False     False  False  False  False  False  False   False  False  False   
1    False     False  False  False  False  False  False   False  False  False   
2    False     False  False  False  False  False  False   False  False  False   
3    False     False  False  False  False  False  False   False  False  False   
4    False     False  False  False  False  False  False   False  False  False   
..     ...       ...    ...    ...    ...    ...    ...     ...    ...    ...   
45   False     False  False  False  False  False  False   False  False  False   
46   False     False  False  False   True  False  False   False  False   True   
47   False     False  False  False  False  False  False   False  False  False   
48   False     False  False  False  False  False  False   False  False   True   
49   False     False  False  False  False  False  False   False  False  False   

    embarked   boat   body  home.dest  
0      False  False   True      False  
1      False  False   True      False  
2      False   True   True      False  
3      False   True  False      False  
4      False   True   True      False  
..       ...    ...    ...        ...  
45     False   True   True      False  
46     False   True   True       True  
47     False  False   True      False  
48     False  False   True      False  
49     False  False   True      False  

[50 rows x 14 columns]

In [21]:
data['ticket'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...  
1304    False
1305    False
1306    False
1307    False
1308    False
Name: ticket, Length: 1309, dtype: bool

In [22]:
pd.isnull(data['ticket'])

0       False
1       False
2       False
3       False
4       False
        ...  
1304    False
1305    False
1306    False
1307    False
1308    False
Name: ticket, Length: 1309, dtype: bool

In [28]:
pd.isnull(data['body']).values.sum()

1188

In [35]:
data['body'].sum()

19458.0

In [30]:
data['body'].head(20)

0       NaN
1       NaN
2       NaN
3     135.0
4       NaN
      ...  
15      NaN
16      NaN
17      NaN
18      NaN
19      NaN
Name: body, Length: 20, dtype: float64

In [32]:
data['body'].count

<bound method Series.count of 0         NaN
1         NaN
2         NaN
3       135.0
4         NaN
        ...  
1304    328.0
1305      NaN
1306    304.0
1307      NaN
1308      NaN
Name: body, Length: 1309, dtype: float64>

In [33]:
1188+121

1309

In [38]:
data.head(5)

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [40]:
data[:5].isnull()

pclass  survived   name    sex    age  sibsp  parch  ticket   fare  cabin  \
0   False     False  False  False  False  False  False   False  False  False   
1   False     False  False  False  False  False  False   False  False  False   
2   False     False  False  False  False  False  False   False  False  False   
3   False     False  False  False  False  False  False   False  False  False   
4   False     False  False  False  False  False  False   False  False  False   

   embarked   boat   body  home.dest  
0     False  False   True      False  
1     False  False   True      False  
2     False   True   True      False  
3     False   True  False      False  
4     False   True   True      False

In [41]:
pd.isnull(data[:5])

pclass  survived   name    sex    age  sibsp  parch  ticket   fare  cabin  \
0   False     False  False  False  False  False  False   False  False  False   
1   False     False  False  False  False  False  False   False  False  False   
2   False     False  False  False  False  False  False   False  False  False   
3   False     False  False  False  False  False  False   False  False  False   
4   False     False  False  False  False  False  False   False  False  False   

   embarked   boat   body  home.dest  
0     False  False   True      False  
1     False  False   True      False  
2     False   True   True      False  
3     False   True  False      False  
4     False   True   True      False

In [45]:
data_2 = pd.DataFrame({'A': [1, None, 3, 4, 5], 'B': [None, 2, 3, 4, 5]})

In [46]:
print(data_2[:5].isnull())

       A      B
0  False   True
1   True  False
2  False  False
3  False  False
4  False  False


In [47]:
print(pd.isnull(data_2[:5]))

       A      B
0  False   True
1   True  False
2  False  False
3  False  False
4  False  False


In [51]:
data.head(5)

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [67]:
print(data['body'].isnull().values.sum())
print(data['body'].notnull().values.sum())

1188
121


In [64]:
len(data['body'])

1309

In [65]:
len(data['body']) - data['body'].isnull().values.sum()

121

In [78]:
import numpy as np

In [85]:
data_3 = pd.DataFrame(
    {'A': [1, np.nan, np.nan, 4],
     'B': [5, 6, np.nan, np.nan],
     'C': [9, 10, 11, 12],
     'D': [np.nan, np.nan, np.nan, np.nan]}
)

In [86]:
data_3

A    B   C   D
0  1.0  5.0   9 NaN
1  NaN  6.0  10 NaN
2  NaN  NaN  11 NaN
3  4.0  NaN  12 NaN

In [88]:
data_3_c = data_3.dropna(axis=1, how='all')
data_3_c

A    B   C
0  1.0  5.0   9
1  NaN  6.0  10
2  NaN  NaN  11
3  4.0  NaN  12

In [89]:
data_3_c_2 = data_3_c.dropna(axis=1, how='any')
data_3_c_2

C
0   9
1  10
2  11
3  12

In [90]:
data_3_c_2 = data_3.dropna(axis=1, how='any')
data_3_c_2

C
0   9
1  10
2  11
3  12

In [ ]:
data.dropna(axis=0, how='any')

In [92]:
data.head(3)

pclass  survived                            name     sex      age  sibsp  \
0       1         1   Allen, Miss. Elisabeth Walton  female  29.0000      0   
1       1         1  Allison, Master. Hudson Trevor    male   0.9167      1   
2       1         0    Allison, Miss. Helen Loraine  female   2.0000      1   

   parch  ticket      fare    cabin embarked boat  body  \
0      0   24160  211.3375       B5        S    2   NaN   
1      2  113781  151.5500  C22 C26        S   11   NaN   
2      2  113781  151.5500  C22 C26        S  NaN   NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON

In [96]:
data_filled = data
data_filled['body'] = data_filled['body'].fillna(0)
data_filled['home.dest'] = data_filled['home.dest'].fillna('Unknown')
data_filled.tail(3)

pclass  survived                       name   sex   age  sibsp  parch  \
1306       3         0  Zakarian, Mr. Mapriededer  male  26.5      0      0   
1307       3         0        Zakarian, Mr. Ortin  male  27.0      0      0   
1308       3         0         Zimmerman, Mr. Leo  male  29.0      0      0   

      ticket   fare cabin embarked boat   body home.dest  
1306    2656  7.225   NaN        C  NaN  304.0   Unknown  
1307    2670  7.225   NaN        C  NaN    0.0   Unknown  
1308  315082  7.875   NaN        S  NaN    0.0   Unknown

In [102]:
data_filled['age'].isnull().values.sum()

263

In [105]:
data_filled['age'] = data_filled['age'].fillna(data_filled['age'].mean())

In [106]:
data_filled['age'].isnull().values.sum()

0

In [107]:
data_filled['age'][1291]

29.8811345124283