# Notes (02)

In [1]:
import numpy as np
from scipy import sparse

# 02. Representation of Data (for Machine Learning)

In [2]:
np.random.seed(42)
X = np.random.random((10, 5))
X[X < 0.7] = 0
print(X)

[[0.         0.95071431 0.73199394 0.         0.        ]
 [0.         0.         0.86617615 0.         0.70807258]
 [0.         0.96990985 0.83244264 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.78517596 0.         0.         0.         0.        ]
 [0.         0.         0.         0.94888554 0.96563203]
 [0.80839735 0.         0.         0.         0.        ]
 [0.         0.         0.         0.9093204  0.        ]
 [0.         0.         0.         0.         0.        ]]


In [3]:
print(X)

[[0.         0.95071431 0.73199394 0.         0.        ]
 [0.         0.         0.86617615 0.         0.70807258]
 [0.         0.96990985 0.83244264 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.78517596 0.         0.         0.         0.        ]
 [0.         0.         0.         0.94888554 0.96563203]
 [0.80839735 0.         0.         0.         0.        ]
 [0.         0.         0.         0.9093204  0.        ]
 [0.         0.         0.         0.         0.        ]]


In [4]:
X_csr = sparse.csr_matrix(X)
print(X_csr)

  (0, 1)	0.9507143064099162
  (0, 2)	0.7319939418114051
  (1, 2)	0.8661761457749352
  (1, 4)	0.7080725777960455
  (2, 1)	0.9699098521619943
  (2, 2)	0.8324426408004217
  (5, 0)	0.7851759613930136
  (6, 3)	0.9488855372533332
  (6, 4)	0.9656320330745594
  (7, 0)	0.8083973481164611
  (8, 3)	0.9093204020787821


In [5]:
print(X_csr.toarray())

[[0.         0.95071431 0.73199394 0.         0.        ]
 [0.         0.         0.86617615 0.         0.70807258]
 [0.         0.96990985 0.83244264 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.78517596 0.         0.         0.         0.        ]
 [0.         0.         0.         0.94888554 0.96563203]
 [0.80839735 0.         0.         0.         0.        ]
 [0.         0.         0.         0.9093204  0.        ]
 [0.         0.         0.         0.         0.        ]]


In [6]:
print(X_csr.shape[1])

5


In [7]:
y = np.random.random(5)
y

array([0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998])

In [8]:
print(X_csr)

  (0, 1)	0.9507143064099162
  (0, 2)	0.7319939418114051
  (1, 2)	0.8661761457749352
  (1, 4)	0.7080725777960455
  (2, 1)	0.9699098521619943
  (2, 2)	0.8324426408004217
  (5, 0)	0.7851759613930136
  (6, 3)	0.9488855372533332
  (6, 4)	0.9656320330745594
  (7, 0)	0.8083973481164611
  (8, 3)	0.9093204020787821


In [9]:
z1 = X_csr.dot(y)
z1

array([1.4246374 , 1.23712815, 1.53388794, 0.        , 0.        ,
       0.76129454, 1.4264401 , 0.78380964, 0.81368477, 0.        ])

In [10]:
X

array([[0.        , 0.95071431, 0.73199394, 0.        , 0.        ],
       [0.        , 0.        , 0.86617615, 0.        , 0.70807258],
       [0.        , 0.96990985, 0.83244264, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.78517596, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.94888554, 0.96563203],
       [0.80839735, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.9093204 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [11]:
z2 = X.dot(y)
z2

array([1.4246374 , 1.23712815, 1.53388794, 0.        , 0.        ,
       0.76129454, 1.4264401 , 0.78380964, 0.81368477, 0.        ])

In [12]:
example_1 = np.arange(0, 5)
example_2 = np.arange(0, 5)
example_3 = np.arange(0+10, 5+10)

np.allclose(example_1, example_2)

True

In [13]:
np.allclose(example_2, example_3)

False

In [20]:
array_1 = np.arange(0, 5)
array_1

array([0, 1, 2, 3, 4])

In [21]:
array_2 = np.arange(0+5, 5+5)
array_2

array([5, 6, 7, 8, 9])

In [23]:
dot_product = array_1.dot(array_2)
dot_product

80

In [25]:
print(sparse.lil_matrix((5,5)))

In [26]:
def find_max_element(numbers):
    max_element = float("-inf")  # Initialize to negative infinity
    for num in numbers:
        if num > max_element:
            max_element = num
    return max_element

# Example usage:
numbers_list = [5, 9, 2, 15, 7]
max_num = find_max_element(numbers_list)
print("Maximum element:", max_num) 

Maximum element: 15


In [29]:
def find_max_element_2(numbers):
    max_element = 0
    for num in numbers:
        if num > max_element:
            max_element = num
    return max_element

In [30]:
numbers_list = [0, 2, 3, 64, 23, 3, 42, 5, 9]

In [31]:
max_num_2 = find_max_element_2(numbers_list)
max_num_2

64

In [64]:
def min_element(num_list):
    lowest_value = float('inf')
    
    for n in num_list:
        if n < lowest_value:
            lowest_value = n
    return lowest_value

In [65]:
numbers_list = [0.05, 12, 42, 12, 0.001, 0.312, -0.3234, -0.031, -120, 231, 21]

In [66]:
min_element(numbers_list)

-120

In [75]:
a193628 = np.random.randint(0, 5, (15, 2))
print(a193628)

[[0 1]
 [0 2]
 [3 0]
 [0 1]
 [1 2]
 [3 1]
 [0 3]
 [3 0]
 [1 0]
 [3 4]
 [4 2]
 [0 0]
 [2 2]
 [2 3]
 [0 3]]


In [84]:
a193628[1, 0]

0

In [82]:
X_lil = sparse.lil_matrix((5, 5))
X_lil

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in List of Lists format>

In [88]:
for i, j in a193628:
    X_lil[i, j] = i + j
    
print(X_lil.toarray(), '\n')
print(X_lil)

[[0. 1. 2. 3. 0.]
 [1. 0. 3. 0. 0.]
 [0. 0. 4. 5. 0.]
 [3. 4. 0. 0. 7.]
 [0. 0. 6. 0. 0.]] 

  (0, 1)	1.0
  (0, 2)	2.0
  (0, 3)	3.0
  (1, 0)	1.0
  (1, 2)	3.0
  (2, 2)	4.0
  (2, 3)	5.0
  (3, 0)	3.0
  (3, 1)	4.0
  (3, 4)	7.0
  (4, 2)	6.0


In [89]:
for i, j in a193628:
    print(i, j)

0 1
0 2
3 0
0 1
1 2
3 1
0 3
3 0
1 0
3 4
4 2
0 0
2 2
2 3
0 3


In [90]:
a193628

array([[0, 1],
       [0, 2],
       [3, 0],
       [0, 1],
       [1, 2],
       [3, 1],
       [0, 3],
       [3, 0],
       [1, 0],
       [3, 4],
       [4, 2],
       [0, 0],
       [2, 2],
       [2, 3],
       [0, 3]])

In [92]:
a200528 = np.random.randint(0, 2, (5, 2))
print(a200528)

[[1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 1]]


In [94]:
X_lil_2 = sparse.lil_matrix((3, 3))

for r, c in a200528:
    X_lil_2[r, c] = r + c
    
print(X_lil_2, '\n')
print(X_lil_2.toarray())

  (0, 1)	1.0
  (1, 0)	1.0
  (1, 1)	2.0 

[[0. 1. 0.]
 [1. 2. 0.]
 [0. 0. 0.]]


In [100]:
X_lil_2

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in List of Lists format>

In [96]:
X_csr = X_lil_2.tocsr()
X_csr

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [98]:
print(X_csr)

  (0, 1)	1.0
  (1, 0)	1.0
  (1, 1)	2.0


In [97]:
X_lil_2

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in List of Lists format>

In [99]:
print(X_lil_2)

  (0, 1)	1.0
  (1, 0)	1.0
  (1, 1)	2.0


In [101]:
X_csc = X_lil_2.tocsc()
X_csc

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Column format>

In [102]:
print(X_csc)

  (1, 0)	1.0
  (0, 1)	1.0
  (1, 1)	2.0
