# Notes (08)

# 08. Bokeh: quick (and partial) summary

In [1]:
x = [0.1, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
y0 = [i**2 for i in x]
y1 = [10**i for i in x]
y2 = [10**(i**2) for i in x]

In [2]:
y0

[0.010000000000000002, 0.25, 1.0, 2.25, 4.0, 6.25, 9.0]

In [3]:
y1

[1.2589254117941673,
 3.1622776601683795,
 10.0,
 31.622776601683793,
 100.0,
 316.22776601683796,
 1000.0]

In [4]:
y2

[1.023292992280754,
 1.7782794100389228,
 10.0,
 177.82794100389228,
 10000.0,
 1778279.410038923,
 1000000000.0]

In [5]:
x_range=[0,10]
x_range

[0, 10]

In [6]:
import numpy as np

In [7]:
N = 10
np.random.random(size=N)*100

array([12.12508474, 36.38253738, 55.10573349, 78.57992741,  5.18525217,
        7.39549253, 81.37676517, 60.23010883, 63.83561746, 33.08264614])

In [8]:
import numpy as np

from bokeh.plotting import figure, output_file, show

# prepare some data
N = 50
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100
radii = np.random.random(size=N) * 1.5
colors = [
    "#%02x%02x%02x" % (int(r), int(g), 150) for r, g in zip(50+2*x, 30+2*y)
]

TOOLS="crosshair,pan,wheel_zoom,box_zoom,reset,box_select,lasso_select"

# create a new plot with the tools above, and explicit ranges
p = figure(tools=TOOLS, x_range=(0,100), y_range=(0,100), width=500, height=500)

# add a circle renderer with vectorized colors and sizes
p.circle(x,y, radius=radii, fill_alpha=0.6, line_color=None)

# show the results
show(p)

In [9]:
x = [1, 2, 3, 4, 5]
y = [3, 7, 8, 5, 1]

p = figure(plot_width=400, plot_height=400)
p.circle(x, y, size=20)
show(p)

In [10]:
from bokeh.sampledata.iris import flowers as df
from bokeh.models import ColumnDataSource

source = ColumnDataSource(df)

In [11]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [12]:
from bokeh.sampledata.airports import data as airports

In [13]:
airports.head(5)

name  elevation             x             y
0             CHINLE MUNICIPAL AIRPORT       1691 -1.219788e+07  4.315889e+06
1  ELY AIRPORT /YELLAND FIELD/ AIRPORT       1908 -1.278414e+07  4.764692e+06
2                TRUCKEE-TAHOE AIRPORT       1798 -1.337387e+07  4.767619e+06
3     GARFIELD COUNTY REGIONAL AIRPORT       1691 -1.199211e+07  4.797343e+06
4           SANTA FE MUNICIPAL AIRPORT       1935 -1.180982e+07  4.248063e+06

In [14]:
from bokeh.sampledata.stocks import AAPL

In [15]:
import pandas as pd

In [16]:
AAPL_df = pd.DataFrame(AAPL)

In [17]:
AAPL_df.head(10)

date    open    high     low   close    volume  adj_close
0  2000-03-01  118.56  132.06  118.50  130.31  38478000      31.68
1  2000-03-02  127.00  127.94  120.69  122.00  11136800      29.66
2  2000-03-03  124.87  128.23  120.00  128.00  11565200      31.12
3  2000-03-06  126.00  129.13  125.00  125.69   7520000      30.56
4  2000-03-07  126.44  127.44  121.12  122.87   9767600      29.87
5  2000-03-08  122.87  123.94  118.56  122.00   9690800      29.66
6  2000-03-09  120.87  125.00  118.25  122.25   9884400      29.72
7  2000-03-10  121.69  127.94  121.00  125.75   8900800      30.57
8  2000-03-13  122.12  126.50  119.50  121.31  10864400      29.50
9  2000-03-14  121.22  124.25  114.00  114.25  15321200      27.78

In [18]:
np.array(AAPL_df['adj_close'])

array([ 31.68,  29.66,  31.12, ..., 438.75, 435.62, 424.83])

In [19]:
np.array(AAPL['adj_close'])

array([ 31.68,  29.66,  31.12, ..., 438.75, 435.62, 424.83])

In [20]:
np.array(AAPL['date'], dtype=np.datetime64)

array(['2000-03-01', '2000-03-02', '2000-03-03', ..., '2013-02-27',
       '2013-02-28', '2013-03-01'], dtype='datetime64[D]')

In [21]:
window_size = 30
window = np.ones(window_size)/float(window_size)

In [22]:
window

array([0.03333333, 0.03333333, 0.03333333, 0.03333333, 0.03333333,
       0.03333333, 0.03333333, 0.03333333, 0.03333333, 0.03333333,
       0.03333333, 0.03333333, 0.03333333, 0.03333333, 0.03333333,
       0.03333333, 0.03333333, 0.03333333, 0.03333333, 0.03333333,
       0.03333333, 0.03333333, 0.03333333, 0.03333333, 0.03333333,
       0.03333333, 0.03333333, 0.03333333, 0.03333333, 0.03333333])

In [23]:
print(np.ones(30))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]


In [24]:
float(30)

30.0

In [25]:
# Define two input sequences
sequence1 = [1, 2, 3, 4]
sequence2 = [0.5, 0.25]

# Perform convolution
result = np.convolve(sequence1, sequence2, mode='full')

print("Result:", result)

Result: [0.5  1.25 2.   2.75 1.  ]


In [26]:
fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
fruits.sort()

In [27]:
fruits

['Apples', 'Grapes', 'Nectarines', 'Pears', 'Plums', 'Strawberries']

In [28]:
fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
years = ['2015', '2016', '2017']

In [29]:
x = [ (fruit, year) for fruit in fruits for year in years ]
x

[('Apples', '2015'),
 ('Apples', '2016'),
 ('Apples', '2017'),
 ('Pears', '2015'),
 ('Pears', '2016'),
 ('Pears', '2017'),
 ('Nectarines', '2015'),
 ('Nectarines', '2016'),
 ('Nectarines', '2017'),
 ('Plums', '2015'),
 ('Plums', '2016'),
 ('Plums', '2017'),
 ('Grapes', '2015'),
 ('Grapes', '2016'),
 ('Grapes', '2017'),
 ('Strawberries', '2015'),
 ('Strawberries', '2016'),
 ('Strawberries', '2017')]

In [31]:
for i, n in enumerate(range(-20, 21)):
    print(i, n)

0 -20
1 -19
2 -18
3 -17
4 -16
5 -15
6 -14
7 -13
8 -12
9 -11
10 -10
11 -9
12 -8
13 -7
14 -6
15 -5
16 -4
17 -3
18 -2
19 -1
20 0
21 1
22 2
23 3
24 4
25 5
26 6
27 7
28 8
29 9
30 10
31 11
32 12
33 13
34 14
35 15
36 16
37 17
38 18
39 19
40 20


In [35]:
abs(25.1)

25.1

In [38]:
from datetime import date

dates=[date(2017, 3, i+1) for i in range(10)]
dates

[datetime.date(2017, 3, 1),
 datetime.date(2017, 3, 2),
 datetime.date(2017, 3, 3),
 datetime.date(2017, 3, 4),
 datetime.date(2017, 3, 5),
 datetime.date(2017, 3, 6),
 datetime.date(2017, 3, 7),
 datetime.date(2017, 3, 8),
 datetime.date(2017, 3, 9),
 datetime.date(2017, 3, 10)]