# <b>Kaggle Learn</b>
# 2. Python

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels as sm
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80
np.set_printoptions(precision = 4, suppress = True)
from pandas import Series, DataFrame
%matplotlib inline

## 1. Hello, Python

In [4]:
spam_amount = 0
print(spam_amount)

spam_amount = spam_amount + 4

if spam_amount > 0:
    print("But I don't want ANY spam!")
    
viking_song = "Spam " * spam_amount
print(viking_song)

0
But I don't want ANY spam!
Spam Spam Spam Spam 


In [5]:
type(spam_amount)

int

In [6]:
type(19.95)

float

In [7]:
print(5/2)
print(6/2)

2.5
3.0


In [9]:
print(5//2)
print(6//2)

2
3


In [10]:
8 - 3 + 2

7

In [11]:
-3 + 4 * 2

5

In [12]:
hat_height_cm = 25
my_height_cm = 190

total_height_meters = hat_height_cm + my_height_cm / 100
print("Height in meters =", total_height_meters, "?")

Height in meters = 26.9 ?


In [13]:
total_height_meters = (hat_height_cm + my_height_cm) / 100
print("Height in meters =", total_height_meters)

Height in meters = 2.15


In [14]:
print(min(1, 2, 3))
print(max(1, 2, 3))

1
3


In [15]:
print(abs(32))
print(abs(-32))

32
32


In [16]:
print(float(10))
print(int(3.33))
print(int('807') + 1)

10.0
3
808


## 2. Functions and Getting Help

In [17]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [18]:
help(help)

Help on _Helper in module _sitebuiltins object:

class _Helper(builtins.object)
 |  Define the builtin 'help'.
 |  
 |  This is a wrapper around pydoc.help that provides a helpful message
 |  when 'help' is typed at the Python interactive prompt.
 |  
 |  Calling help() at the Python prompt starts an interactive help session.
 |  Calling help(thing) prints help for the python object 'thing'.
 |  
 |  Methods defined here:
 |  
 |  __call__(self, *args, **kwds)
 |      Call self as a function.
 |  
 |  __repr__(self)
 |      Return repr(self).
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



In [19]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [20]:
def least_difference(a, b, c):
    diff1 = abs(a - b)
    diff2 = abs(b - c)
    diff3 = abs(a - c)
    return min(diff1, diff2, diff3)

In [21]:
print(
    least_difference(1, 10, 100),
    least_difference(1, 10, 10),
    least_difference(5, 6, 7)
)

9 0 1


In [22]:
help(least_difference)

Help on function least_difference in module __main__:

least_difference(a, b, c)



In [23]:
def least_difference(a, b, c):
    """Return the smallest difference between any two numbers
    among a, b and c.
    
    >>> least_difference(1, 5, -5)
    4
    """
    diff1 = abs(a - b)
    diff2 = abs(b - c)
    diff3 = abs(a - c)
    return min(diff1, diff2, diff3)

In [24]:
help(least_difference)

Help on function least_difference in module __main__:

least_difference(a, b, c)
    Return the smallest difference between any two numbers
    among a, b and c.
    
    >>> least_difference(1, 5, -5)
    4



In [25]:
def least_difference(a, b, c):
    """Return the smallest difference between any two numbers
    among a, b and c.
    """
    diff1 = abs(a - b)
    diff2 = abs(b - c)
    diff3 = abs(a - c)
    min(diff1, diff2, diff3)
    
print(
    least_difference(1, 10, 100),
    least_difference(1, 10, 10),
    least_difference(5, 6, 7)
)

None None None


In [26]:
mystery = print()
print(mystery)


None


In [27]:
print(1, 2, 3, sep = ' < ')

1 < 2 < 3


In [28]:
print(1, 2, 3)

1 2 3


In [29]:
def greet(who = "Colin"):
    print("Hello,", who)
    
greet()
greet(who = "Kaggle")
greet("world")

Hello, Colin
Hello, Kaggle
Hello, world


In [30]:
def mult_by_five(x):
    return 5 * x
    
def call(fn, arg):
    "Call fn on arg"""
    return fn(arg)

def squared_call(fn, arg):
    """Call fn on the result of calling fn on arg"""
    return fn(fn(arg))

print(
    call(mult_by_five, 1),
    squared_call(mult_by_five, 1),
    sep = '\n' # '\n' is the newline character - it starts a new line
)

5
25


In [31]:
def mod_5(x):
    """Return the remainder of x after dividing by 5"""
    return x % 5

print(
    'Which number is biggest?',
    max(100, 51, 14),
    'Which number is biggest modulo 5?',
    max(100, 51, 14, key = mod_5),
    sep = '\n'
)

Which number is biggest?
100
Which number is biggest modulo 5?
14


In [32]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



## 3. Booleans and Conditionals

In [33]:
x = True
print(x)
print(type(x))

True
<class 'bool'>


In [34]:
def can_run_for_president(age):
    """Can someone of the given age run for president in the US?"""
    # The US Constitution says you must be at least 35 years old
    return age >= 35

print("Can a 19-year-old run for president?", can_run_for_president(19))
print("Can a 45-year-old run for president?", can_run_for_president(45))

Can a 19-year-old run for president? False
Can a 45-year-old run for president? True


In [35]:
3.0 == 3

True

In [36]:
'3' == 3

False

In [37]:
def is_odd(n):
    return (n % 2) == 1

print("Is 100 odd?", is_odd(100))
print("Is -1 odd?", is_odd(-1))

Is 100 odd? False
Is -1 odd? True


In [38]:
def can_run_for_president(age, is_natural_born_citizen):
    """Can someone of the given age and citizenship status run for president in the US?"""
    # The US Constitution says you must be a natural born citizen *and* at least 35 years old
    return is_natural_born_citizen and (age >= 35)

print(can_run_for_president(19, True))
print(can_run_for_president(55, False))
print(can_run_for_president(55, True))

False
False
True


In [39]:
True or True and False

True

In [42]:
def inspect(x):
    if x == 0:
        print(x, "is zero")
    elif x > 0:
        print(x, "is positive")
    elif x < 0:
        print(x, "is negative")
    else:
        print(x, "is unlike anything I've ever seen...")

inspect(0)
inspect(-15)

0 is zero
-15 is negative


In [43]:
def f(x):
    if x > 0:
        print("Only printed when x is positive; x =", x)
        print("Also only printed when x is positive; x =", x)
    print("Always printed, regardless of x's value; x =", x)

f(1)
f(0)

Only printed when x is positive; x = 1
Also only printed when x is positive; x = 1
Always printed, regardless of x's value; x = 1
Always printed, regardless of x's value; x = 0


In [46]:
print(bool(1))
print(bool(0)) # 0 is treated as False
print(bool("asf"))
print(bool("")) # An empty string is treated as False

True
False
True
False


In [47]:
if 0:
    print(0)
elif "spam":
    print("spam")

spam


## 4. Lists

In [48]:
primes = [2, 3, 5, 7]

In [49]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

In [50]:
hands = [
    ['J', 'Q', 'K'],
    ['2', '2', '2'],
    ['6', 'A', 'K']
]

hands = [['J', 'Q', 'K'], ['2', '2', '2'], ['6', 'A', 'K']]

In [51]:
my_favourite_things = [32, 'raindrops on roses', help]

In [52]:
planets[0]

'Mercury'

In [53]:
planets[1]

'Venus'

In [54]:
planets[-1]

'Neptune'

In [55]:
planets[-2]

'Uranus'

In [57]:
planets[:3]

['Mercury', 'Venus', 'Earth']

In [57]:
planets[:3]

['Mercury', 'Venus', 'Earth']

In [58]:
planets[3:]

['Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

In [59]:
planets[1:-1]

['Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus']

In [60]:
planets[-3:]

['Saturn', 'Uranus', 'Neptune']

In [61]:
planets[3] = 'Malacandra'
planets

['Mercury',
 'Venus',
 'Earth',
 'Malacandra',
 'Jupiter',
 'Saturn',
 'Uranus',
 'Neptune']

In [62]:
planets[:3] = ['Mur', 'Vee', 'Ur']
print(planets)
planets[:4] = ['Mercury', 'Venus', 'Earth', 'Mars']

['Mur', 'Vee', 'Ur', 'Malacandra', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']


In [63]:
len(planets)

8

In [64]:
sorted(planets)

['Earth', 'Jupiter', 'Mars', 'Mercury', 'Neptune', 'Saturn', 'Uranus', 'Venus']

In [65]:
primes = [2, 3, 5, 7]
sum(primes)

17

In [66]:
max(primes)

7

In [67]:
x = 12
print(x.imag)
c = 12 + 3j
print(c.imag)

0
3.0


In [68]:
x.bit_length

<function int.bit_length()>

In [69]:
x.bit_length()

4

In [70]:
help(x.bit_length)

Help on built-in function bit_length:

bit_length() method of builtins.int instance
    Number of bits necessary to represent self in binary.
    
    >>> bin(37)
    '0b100101'
    >>> (37).bit_length()
    6



In [71]:
planets.append('Pluto')

In [72]:
help(planets.append)

Help on built-in function append:

append(object, /) method of builtins.list instance
    Append object to the end of the list.



In [73]:
planets

['Mercury',
 'Venus',
 'Earth',
 'Mars',
 'Jupiter',
 'Saturn',
 'Uranus',
 'Neptune',
 'Pluto']

In [74]:
planets.pop()

'Pluto'

In [75]:
planets

['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

In [76]:
planets.index("Earth")

2

In [77]:
"Earth" in planets

True

In [78]:
"Calbefraques" in planets

False

In [79]:
help(planets)

Help on list object:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate sign

In [80]:
t = (1, 2, 3)

In [81]:
t = 1, 2, 3
t

(1, 2, 3)

In [83]:
# t[0] = 100 # returns an error since tuples are immutable

In [84]:
x = 0.125
x.as_integer_ratio()

(1, 8)

In [85]:
numerator, denominator = x.as_integer_ratio()
print(numerator / denominator)

0.125


In [86]:
a = 1
b = 0
a, b = b, a
print(a, b)

0 1


## 5. Loops and List Comprehensions

In [2]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']

for planet in planets:
    print(planet, end = ' ')

Mercury Venus Earth Mars Jupiter Saturn Uranus Neptune 

In [4]:
for i, planet in enumerate(planets):
    print(i, planet)

0 Mercury
1 Venus
2 Earth
3 Mars
4 Jupiter
5 Saturn
6 Uranus
7 Neptune


In [7]:
multiplicands = (2, 2, 2, 3, 3, 5)
product = 1

for mult in multiplicands:
    product = product * mult
product

360

In [8]:
s = 'steganograpHy is the practicE of conceaLing a file, message, image, or video within another fiLe, message, image, Or video.'
msg = ''

for char in s:
    if char.isupper():
        print(char, end = '')

HELLO

In [9]:
for i in range(5):
    print("Doing important work. i =", i)

Doing important work. i = 0
Doing important work. i = 1
Doing important work. i = 2
Doing important work. i = 3
Doing important work. i = 4


In [10]:
i = 0
while i < 10:
    print(i, end = ' ')
    i += 1

0 1 2 3 4 5 6 7 8 9 

In [12]:
squares = [n**2 for n in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [13]:
squares = []
for n in range(10):
    squares.append(n**2)
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [14]:
short_planets = [planet for planet in planets if len(planet) < 6]
short_planets

['Venus', 'Earth', 'Mars']

In [15]:
loud_short_planets = [planet.upper() + '!' for planet in planets if len(planet) < 6]
loud_short_planets

['VENUS!', 'EARTH!', 'MARS!']

In [16]:
[32 for planet in planets]

[32, 32, 32, 32, 32, 32, 32, 32]

In [17]:
def count_negatives(nums):
    """Return the number of negative numbers in the given list.
    
    >>> count_negatives([5, -1, -2, 0, 3])
    2
    """
    n_negative = 0
    for num in nums:
        if num < 0:
            n_negative = n_negative + 1
    return n_negative

In [18]:
def count_negatives(nums):
    return len([num for num in nums if num < 0])

In [19]:
def count_negatives(nums):
    return sum([num < 0 for num in nums])

## 2.6 Strings and Dictionaries

In [20]:
x = 'Pluto is a planet'
y = "Pluto is a planet"
x == y

True

In [21]:
print("Pluto's a planet!")
print('My dog is named "Pluto"')

Pluto's a planet!
My dog is named "Pluto"


In [22]:
'Pluto\'s a planet!'

"Pluto's a planet!"

In [23]:
hello = "hello\nworld"
print(hello)

hello
world


In [25]:
triplequoted_hello = """hello
world"""
print(triplequoted_hello)
triplequoted_hello == hello

hello
world


True

In [26]:
print("hello")
print("world")
print("hello", end='') # default value is '\n'
print("pluto", end='') # default value is '\n'

hello
world
hellopluto

In [27]:
planet = 'Pluto'
planet[0]

'P'

In [28]:
planet[-3:]

'uto'

In [29]:
len(planet)

5

In [30]:
[char + '!' for char in planet]

['P!', 'l!', 'u!', 't!', 'o!']

In [31]:
claim = "Pluto is a planet!"
claim.upper()

'PLUTO IS A PLANET!'

In [32]:
claim.lower()

'pluto is a planet!'

In [33]:
claim.index('plan')

11

In [34]:
claim.startswith(planet)

True

In [35]:
claim.endswith('planet')

False

In [36]:
list('abc')

['a', 'b', 'c']

In [37]:
words = claim.split()
words

['Pluto', 'is', 'a', 'planet!']

In [38]:
datestr = '1956-01-31'
year, month, day = datestr.split('-')

In [39]:
'/'.join([month, day, year])

'01/31/1956'

In [40]:
' 👏 '.join([word.upper() for word in words])

'PLUTO 👏 IS 👏 A 👏 PLANET!'

In [41]:
planet + ', we miss you.'

'Pluto, we miss you.'

In [43]:
position = 9
planet + ", you'll always be the " + str(position) + "th planet to me."

"Pluto, you'll always be the 9th planet to me."

In [44]:
f"{planet}, you'll always be the {position}th planet to me."

"Pluto, you'll always be the 9th planet to me."

In [45]:
"{}, you'll always be the {}th planet to me.".format(planet, position)

"Pluto, you'll always be the 9th planet to me."

In [46]:
pluto_mass = 1.303 * 10**22
earth_mass = 5.9722 * 10**24
population = 52910390

f"{planet} weights about {pluto_mass:.2} kilograms ({(pluto_mass/earth_mass):.3%} of Earth's mass. It is home to {population:,} Plutonians."

"Pluto weights about 1.3e+22 kilograms (0.218% of Earth's mass. It is home to 52,910,390 Plutonians."

In [47]:
pluto_mass = 1.303 * 10**22
earth_mass = 5.9722 * 10**24
population = 52910390
#         2 decimal points   3 decimal points, format as percent     separate with commas
"{} weighs about {:.2} kilograms ({:.3%} of Earth's mass). It is home to {:,} Plutonians.".format(
    planet, pluto_mass, pluto_mass / earth_mass, population,
)

"Pluto weighs about 1.3e+22 kilograms (0.218% of Earth's mass). It is home to 52,910,390 Plutonians."

In [48]:
# Referring to format() arguments by index, starting from 0
s = """Pluto's a {0}.
No, it's a {1}.
{0}!
{1}!""".format('planet', 'dwarf planet')
print(s)

Pluto's a planet.
No, it's a dwarf planet.
planet!
dwarf planet!


In [49]:
numbers = {'one': 1, 'two': 2, 'three': 3}

In [50]:
numbers['one']

1

In [51]:
numbers['eleven'] = 11
numbers

{'one': 1, 'two': 2, 'three': 3, 'eleven': 11}

In [52]:
numbers['one'] = 'Pluto'
numbers

{'one': 'Pluto', 'two': 2, 'three': 3, 'eleven': 11}

In [53]:
planets = ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune']
planet_to_initial = {planet: planet[0] for planet in planets}
planet_to_initial

{'Mercury': 'M',
 'Venus': 'V',
 'Earth': 'E',
 'Mars': 'M',
 'Jupiter': 'J',
 'Saturn': 'S',
 'Uranus': 'U',
 'Neptune': 'N'}

In [54]:
'Saturn' in planet_to_initial

True

In [55]:
'Betelgeuse' in planet_to_initial

False

In [56]:
for k in numbers:
    print("{} = {}".format(k, numbers[k]))

one = Pluto
two = 2
three = 3
eleven = 11


In [57]:
for k in numbers:
    print(f"{k} = {numbers[k]}")

one = Pluto
two = 2
three = 3
eleven = 11


In [61]:
' '.join(sorted(planet_to_initial.values()))

'E J M M N S U V'

In [62]:
planet_to_initial

{'Mercury': 'M',
 'Venus': 'V',
 'Earth': 'E',
 'Mars': 'M',
 'Jupiter': 'J',
 'Saturn': 'S',
 'Uranus': 'U',
 'Neptune': 'N'}

In [68]:
for planet, initial in planet_to_initial.items():
    print(f"{planet.rjust(10)} begins with \"{initial}\"")

   Mercury begins with "M"
     Venus begins with "V"
     Earth begins with "E"
      Mars begins with "M"
   Jupiter begins with "J"
    Saturn begins with "S"
    Uranus begins with "U"
   Neptune begins with "N"


In [66]:
help(planet.rjust)

Help on built-in function rjust:

rjust(width, fillchar=' ', /) method of builtins.str instance
    Return a right-justified string of length width.
    
    Padding is done using the specified fill character (default is a space).



## 7. Working with External Libraries

In [71]:
import math

print("It's math! It has type {}".format(type(math)))

It's math! It has type <class 'module'>


In [72]:
print(dir(math))

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [73]:
print("pi to 4 significant digits = {:.4}".format(math.pi))

pi to 4 significant digits = 3.142


In [74]:
math.log(32, 2)

5.0

In [75]:
help(math.log)

Help on built-in function log in module math:

log(...)
    log(x, [base=math.e])
    Return the logarithm of x to the given base.
    
    If the base not specified, returns the natural logarithm (base e) of x.



In [76]:
import math as mt
mt.pi

3.141592653589793

In [77]:
import math
mt = math

In [78]:
from math import *
print(pi, log(32, 2))

3.141592653589793 5.0


In [79]:
from math import log, pi
from numpy import asarray

In [80]:
import numpy
print("numpy.random is a", type(numpy.random))
print("it contains names such as...",
      dir(numpy.random)[-15:]
     )

numpy.random is a <class 'module'>
it contains names such as... ['seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'test', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf']


In [81]:
rolls = numpy.random.randint(low=1, high=6, size=10)
rolls

array([1, 2, 3, 4, 1, 5, 1, 2, 1, 3])

In [82]:
type(rolls)

numpy.ndarray

In [83]:
print(dir(rolls))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [84]:
rolls.mean()

2.3

In [85]:
rolls.tolist()

[1, 2, 3, 4, 1, 5, 1, 2, 1, 3]

In [86]:
list(rolls)

[1, 2, 3, 4, 1, 5, 1, 2, 1, 3]

In [87]:
help(rolls.ravel)

Help on built-in function ravel:

ravel(...) method of numpy.ndarray instance
    a.ravel([order])
    
    Return a flattened array.
    
    Refer to `numpy.ravel` for full documentation.
    
    See Also
    --------
    numpy.ravel : equivalent function
    
    ndarray.flat : a flat iterator on the array.



In [88]:
rolls + 10

array([11, 12, 13, 14, 11, 15, 11, 12, 11, 13])

In [89]:
rolls <= 3

array([ True,  True,  True, False,  True, False,  True,  True,  True,
        True])

In [90]:
xlist = [[1,2,3],[2,4,6],]
# Create a 2-dimensional array
x = numpy.asarray(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]


In [105]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [103]:
x[1,-1]

6

In [108]:
# import tensorflow as tf
# # Create two constants, each with value 1
# a = tf.constant(1)
# b = tf.constant(1)
# # Add them together to get...
# a + b

In [109]:
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
