# <b>Python for Data Analysis</b>
# 7.  Data Cleaning and Preparation

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels as sm
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80
np.set_printoptions(precision=4, suppress=True)
from pandas import Series, DataFrame

## 7.1 Handling Missing Data

In [2]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [3]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [5]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [6]:
float_data = pd.Series([1, 2, None], dtype = 'float64')
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [7]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

### Filtering Out Missing Data

In [8]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [9]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [13]:
data.dropna(how = "all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [14]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [15]:
data[4] = np.nan
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [16]:
data.dropna(axis = "columns", how = "all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df

0         1         2
0  0.811792  0.312147 -0.762631
1  0.303413 -1.819128 -1.080864
2  0.468674 -2.027686  1.965170
3  0.613158  1.540092 -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [18]:
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

0         1         2
0  0.811792       NaN       NaN
1  0.303413       NaN       NaN
2  0.468674       NaN  1.965170
3  0.613158       NaN -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [19]:
df.dropna()

0         1         2
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [20]:
df.dropna(thresh = 2)

0         1         2
2  0.468674       NaN  1.965170
3  0.613158       NaN -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

### Filling In Missing Data

In [21]:
df

0         1         2
0  0.811792       NaN       NaN
1  0.303413       NaN       NaN
2  0.468674       NaN  1.965170
3  0.613158       NaN -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [22]:
df.fillna(0)

0         1         2
0  0.811792  0.000000  0.000000
1  0.303413  0.000000  0.000000
2  0.468674  0.000000  1.965170
3  0.613158  0.000000 -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [23]:
df.fillna(df.mean())

0         1         2
0  0.811792  0.442686  0.086863
1  0.303413  0.442686  0.086863
2  0.468674  0.442686  1.965170
3  0.613158  0.442686 -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [24]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.811792  0.500000  0.000000
1  0.303413  0.500000  0.000000
2  0.468674  0.500000  1.965170
3  0.613158  0.500000 -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [25]:
col1mean = df[0].mean()
col1mean

0.3447694416065867

In [26]:
col2mean = df[1].mean()
col2mean

0.4426859700447698

In [27]:
col3mean = df[2].mean()
col3mean

0.08686303497060649

In [30]:
df.fillna({0: col1mean, 
           1: col2mean, 
           2: col3mean})

0         1         2
0  0.811792  0.442686  0.086863
1  0.303413  0.442686  0.086863
2  0.468674  0.442686  1.965170
3  0.613158  0.442686 -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [32]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df

0         1         2
0  0.474530 -0.393077 -0.967331
1 -0.655516 -0.444019  0.805094
2  0.197483 -0.031589 -0.919530
3 -1.436841  0.402624  0.191649
4 -0.754962  1.280132  0.120549
5 -0.261049 -0.579450  1.253678

In [34]:
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

0         1         2
0  0.474530 -0.393077 -0.967331
1 -0.655516 -0.444019  0.805094
2  0.197483       NaN -0.919530
3 -1.436841       NaN  0.191649
4 -0.754962       NaN       NaN
5 -0.261049       NaN       NaN

In [35]:
df.fillna(method = "ffill")

0         1         2
0  0.474530 -0.393077 -0.967331
1 -0.655516 -0.444019  0.805094
2  0.197483 -0.444019 -0.919530
3 -1.436841 -0.444019  0.191649
4 -0.754962 -0.444019  0.191649
5 -0.261049 -0.444019  0.191649

In [36]:
df.fillna(method = "ffill", limit = 2)

0         1         2
0  0.474530 -0.393077 -0.967331
1 -0.655516 -0.444019  0.805094
2  0.197483 -0.444019 -0.919530
3 -1.436841 -0.444019  0.191649
4 -0.754962       NaN  0.191649
5 -0.261049       NaN  0.191649

In [37]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [38]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 7.2 Data Transformation

### Removing Duplicates

In [39]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [40]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [42]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [43]:
data["v1"] = range(7)

In [44]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [45]:
data.drop_duplicates(subset = ["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [46]:
data.drop_duplicates(subset = ["k2"])

k1  k2  v1
0  one   1   0
2  one   2   2
3  two   3   3
5  two   4   5

In [47]:
data.drop_duplicates(["k1", "k2"], keep = "last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming Data Using a Function or Mapping

In [48]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [49]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [51]:
data["animal"] = data["food"].map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [52]:
def get_animal(x):
    return meat_to_animal[x]

In [53]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### Replacing Values

In [54]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [55]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [56]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [62]:
data.replace([data[data < 0]], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [63]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [64]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renaming Axis Indexes

In [65]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index = ["Ohio", "Colorado", "New York"],
                    columns = ["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [66]:
def transform(x):
    return x[:4].upper()

In [68]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [74]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [75]:
data.index

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [76]:
data.index = data.index.map(transform)

In [77]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [78]:
data.rename(index = str.title, columns = str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [79]:
data.rename(index = {"OHIO": "INDIANA"},
            columns = {"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

### Discretization and Binning

In [80]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [81]:
bins = [18, 25, 35, 60, 100]

In [82]:
age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [83]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [84]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [85]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [86]:
pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [87]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [88]:
pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [89]:
pd.cut(ages, bins, right = False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [90]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [91]:
pd.cut(ages, bins, labels = group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [92]:
data = np.random.uniform(size = 20)

In [93]:
pd.cut(data, 4, precision = 2)

[(0.77, 1.0], (0.53, 0.77], (0.069, 0.3], (0.069, 0.3], (0.069, 0.3], ..., (0.3, 0.53], (0.53, 0.77], (0.069, 0.3], (0.069, 0.3], (0.53, 0.77]]
Length: 20
Categories (4, interval[float64, right]): [(0.069, 0.3] < (0.3, 0.53] < (0.53, 0.77] < (0.77, 1.0]]

In [94]:
data = np.random.standard_normal(1000)
quartiles = pd.qcut(data, 4, precision = 2)
quartiles

[(0.71, 3.76], (0.71, 3.76], (0.71, 3.76], (-0.68, 0.014], (0.71, 3.76], ..., (-0.68, 0.014], (-0.68, 0.014], (0.71, 3.76], (-3.82, -0.68], (0.71, 3.76]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.82, -0.68] < (-0.68, 0.014] < (0.014, 0.71] < (0.71, 3.76]]

In [95]:
pd.value_counts(quartiles)

(-3.82, -0.68]    250
(-0.68, 0.014]    250
(0.014, 0.71]     250
(0.71, 3.76]      250
dtype: int64

In [96]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.8129999999999997, -1.25]    100
(-1.25, 0.0142]                 400
(0.0142, 1.284]                 400
(1.284, 3.762]                  100
dtype: int64

In [102]:
dfTest = np.arange(100)
dfTest

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [108]:
pd.cut(dfTest, [0, 15, 50, 60, 100]).value_counts()

(0, 15]      15
(15, 50]     35
(50, 60]     10
(60, 100]    39
dtype: int64

In [108]:
pd.cut(dfTest, [0, 15, 50, 60, 100]).value_counts()

(0, 15]      15
(15, 50]     35
(50, 60]     10
(60, 100]    39
dtype: int64

### Detecting and Filtering Outliers

In [109]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data

0         1         2         3
0   -1.417758  0.743890  0.675199 -0.886544
1    1.979514 -0.129467 -0.763258  0.584969
2   -0.519349  1.125507 -1.263263  0.337187
3    0.884150  0.061580 -0.696149 -1.581202
4   -0.543634 -2.056615 -0.970453 -0.057096
..        ...       ...       ...       ...
995 -0.138223 -0.230692  1.113294  1.358675
996 -0.467795 -1.124462  1.382013 -2.062655
997 -0.407402  0.355065  0.553154  0.789942
998 -0.353654  0.312514  0.215295  0.012161
999  0.316937 -0.925420  0.735794  1.409310

[1000 rows x 4 columns]

In [110]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.005209     0.013854    -0.040344     0.042829
std       1.019918     1.003715     0.963698     0.994820
min      -3.381881    -2.798622    -2.975792    -3.002567
25%      -0.679878    -0.647186    -0.715405    -0.630336
50%       0.002293     0.050315    -0.062652     0.016541
75%       0.674035     0.660457     0.629786     0.731469
max       3.872668     3.470999     2.948149     2.843463

In [111]:
data[2]

0      0.675199
1     -0.763258
2     -1.263263
3     -0.696149
4     -0.970453
         ...   
995    1.113294
996    1.382013
997    0.553154
998    0.215295
999    0.735794
Name: 2, Length: 1000, dtype: float64

In [112]:
col = data[2]

In [117]:
col[col < -2.7]

568   -2.975792
752   -2.906603
Name: 2, dtype: float64

In [117]:
col[col < -2.7]

568   -2.975792
752   -2.906603
Name: 2, dtype: float64

In [117]:
col[col < -2.7]

568   -2.975792
752   -2.906603
Name: 2, dtype: float64

In [118]:
data[(data.abs() > 3).any(axis = "columns")]

0         1         2         3
95  -0.283141  0.330015 -0.421116 -3.002567
142  3.003804 -1.110863 -1.964108  0.948988
200 -3.381881 -0.951867 -0.359264 -0.959585
467  1.054170  3.470999  0.794451 -1.047008
639  3.872668  0.602980 -1.582059 -0.951343
936 -3.004480  0.324877 -0.982725  0.831026

In [126]:
data[data.abs() > 3] = np.sign(data) * 3

In [127]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.005699     0.013383    -0.040344     0.042832
std       1.015743     1.002200     0.963698     0.994812
min      -3.000000    -2.798622    -2.975792    -3.000000
25%      -0.679878    -0.647186    -0.715405    -0.630336
50%       0.002293     0.050315    -0.062652     0.016541
75%       0.674035     0.660457     0.629786     0.731469
max       3.000000     3.000000     2.948149     2.843463

In [129]:
test1 = np.arange(10)
test1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
test1[test1 < 5] = np.sign(test1[test1 < 5]) * 10

In [134]:
test1

array([ 0, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [135]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0  1.0 -1.0
1  1.0 -1.0 -1.0  1.0
2 -1.0  1.0 -1.0  1.0
3  1.0  1.0 -1.0 -1.0
4 -1.0 -1.0 -1.0 -1.0

### Permutation and Random Sampling

In [2]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [12]:
sampler = np.random.permutation(5)
sampler

array([4, 0, 1, 3, 2])

In [35]:
list(df.index)

[0, 1, 2, 3, 4]

In [27]:
np.random.permutation(list(df))

array([4, 0, 2, 6, 1, 5, 3])

In [28]:
df.take(sampler)

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [30]:
df.iloc[sampler]

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [77]:
df.take(np.random.permutation(list(df)), axis = "columns")

6   2   4   5   3   1   0
0   6   2   4   5   3   1   0
1  13   9  11  12  10   8   7
2  20  16  18  19  17  15  14
3  27  23  25  26  24  22  21
4  34  30  32  33  31  29  28

In [77]:
df.take(np.random.permutation(list(df)), axis = "columns")

6   2   4   5   3   1   0
0   6   2   4   5   3   1   0
1  13   9  11  12  10   8   7
2  20  16  18  19  17  15  14
3  27  23  25  26  24  22  21
4  34  30  32  33  31  29  28

In [80]:
column_sampler = np.random.permutation(7)
column_sampler

array([0, 1, 4, 6, 2, 5, 3])

In [81]:
df.take(column_sampler, axis = "columns")

0   1   4   6   2   5   3
0   0   1   4   6   2   5   3
1   7   8  11  13   9  12  10
2  14  15  18  20  16  19  17
3  21  22  25  27  23  26  24
4  28  29  32  34  30  33  31

In [91]:
df.sample(n = 3)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6

In [92]:
choices = pd.Series([5, 7, -1, 6, 4])
choices

0    5
1    7
2   -1
3    6
4    4
dtype: int64

In [111]:
choices.sample(n = 10, replace = True)

2   -1
3    6
3    6
0    5
1    7
0    5
1    7
4    4
2   -1
1    7
dtype: int64

### Computing Indicator/Dummy Variables

In [113]:
df = pd.DataFrame({"key": list("bbacab"),
                   "data1": range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [118]:
pd.get_dummies(df["key"])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [118]:
pd.get_dummies(df["key"])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [117]:
dummies = pd.get_dummies(df["key"], prefix = "key", dtype = float)
df_with_dummy = df[["data1"]].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [119]:
mnames = ["movie_id", "title", "genres"]

In [120]:
movies = pd.read_table("datasets/movielens/movies.dat",
                       sep = "::",
                       header = None,
                       names = mnames,
                       engine = "python")
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [122]:
dummies = movies["genres"].str.get_dummies("|")
dummies

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0          0          0          1           1       1      0            0   
1          0          1          0           1       0      0            0   
2          0          0          0           0       1      0            0   
3          0          0          0           0       1      0            0   
4          0          0          0           0       1      0            0   
...      ...        ...        ...         ...     ...    ...          ...   
3878       0          0          0           0       1      0            0   
3879       0          0          0           0       0      0            0   
3880       0          0          0           0       0      0            0   
3881       0          0          0           0       0      0            0   
3882       0          0          0           0       0      0            0   

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
0         0        0          0       0        0        0        0       0   
1         0        1          0       0        0        0        0       0   
2         0        0          0       0        0        0        1       0   
3         1        0          0       0        0        0        0       0   
4         0        0          0       0        0        0        0       0   
...     ...      ...        ...     ...      ...      ...      ...     ...   
3878      0        0          0       0        0        0        0       0   
3879      1        0          0       0        0        0        0       0   
3880      1        0          0       0        0        0        0       0   
3881      1        0          0       0        0        0        0       0   
3882      1        0          0       0        0        0        0       0   

      Thriller  War  Western  
0            0    0        0  
1            0    0        0  
2            0    0        0  
3            0    0        0  
4            0    0        0  
...        ...  ...      ...  
3878         0    0        0  
3879         0    0        0  
3880         0    0        0  
3881         0    0        0  
3882         1    0        0  

[3883 rows x 18 columns]

In [123]:
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [124]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))
movies_windic

movie_id                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
3878      3948             Meet the Parents (2000)   
3879      3949          Requiem for a Dream (2000)   
3880      3950                    Tigerland (2000)   
3881      3951             Two Family House (2000)   
3882      3952               Contender, The (2000)   

                            genres  Genre_Action  Genre_Adventure  \
0      Animation|Children's|Comedy             0                0   
1     Adventure|Children's|Fantasy             0                1   
2                   Comedy|Romance             0                0   
3                     Comedy|Drama             0                0   
4                           Comedy             0                0   
...                            ...           ...              ...   
3878                        Comedy             0                0   
3879                         Drama             0                0   
3880                         Drama             0                0   
3881                         Drama             0                0   
3882                Drama|Thriller             0                0   

      Genre_Animation  Genre_Children's  Genre_Comedy  Genre_Crime  \
0                   1                 1             1            0   
1                   0                 1             0            0   
2                   0                 0             1            0   
3                   0                 0             1            0   
4                   0                 0             1            0   
...               ...               ...           ...          ...   
3878                0                 0             1            0   
3879                0                 0             0            0   
3880                0                 0             0            0   
3881                0                 0             0            0   
3882                0                 0             0            0   

      Genre_Documentary  ...  Genre_Fantasy  Genre_Film-Noir  Genre_Horror  \
0                     0  ...              0                0             0   
1                     0  ...              1                0             0   
2                     0  ...              0                0             0   
3                     0  ...              0                0             0   
4                     0  ...              0                0             0   
...                 ...  ...            ...              ...           ...   
3878                  0  ...              0                0             0   
3879                  0  ...              0                0             0   
3880                  0  ...              0                0             0   
3881                  0  ...              0                0             0   
3882                  0  ...              0                0             0   

      Genre_Musical  Genre_Mystery  Genre_Romance  Genre_Sci-Fi  \
0                 0              0              0             0   
1                 0              0              0             0   
2                 0              0              1             0   
3                 0              0              0             0   
4                 0              0              0             0   
...             ...            ...            ...           ...   
3878              0              0              0             0   
3879              0              0              0             0   
3880              0              0              0             0   
3881              0              0              0             0   
3882         

In [125]:
movies_windic.iloc[0]

movie_id                                     1
title                         Toy Story (1995)
genres             Animation|Children's|Comedy
Genre_Action                                 0
Genre_Adventure                              0
                              ...             
Genre_Romance                                0
Genre_Sci-Fi                                 0
Genre_Thriller                               0
Genre_War                                    0
Genre_Western                                0
Name: 0, Length: 21, dtype: object

In [126]:
np.random.seed(12345)

In [127]:
values = np.random.uniform(size = 10)
values

array([0.9296, 0.3164, 0.1839, 0.2046, 0.5677, 0.5955, 0.9645, 0.6532,
       0.7489, 0.6536])

In [128]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [129]:
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## 7.3 Extension Data Types

In [130]:
s = pd.Series([1, 2, 3, None])
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [131]:
s.dtype

dtype('float64')

In [132]:
s = pd.Series([1, 2, 3, None], dtype = pd.Int64Dtype())
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [133]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [134]:
s.dtype

Int64Dtype()

In [135]:
s[3]

<NA>

In [136]:
s[3] is pd.NA

True

In [137]:
s = pd.Series([1, 2, 3, None], dtype = "Int64")

In [140]:
s = pd.Series(["one", "two", None, "three"], dtype = pd.StringDtype())
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [141]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                   "C": [False, None, False, True]})
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [142]:
df["A"] = df["A"].astype("Int64")
df["B"] = df["B"].astype("string")
df["C"] = df["C"].astype("boolean")
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

## 7.4 String Manipulation

### Python Built-In String Object Methods

In [143]:
val = "a,b,  guido"

In [144]:
val.split(",")

['a', 'b', '  guido']

In [145]:
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [146]:
first, second, third = pieces

In [147]:
first + "::" + second + "::" + third

'a::b::guido'

In [148]:
"guido" in val

True

In [149]:
val.index(",")

1

In [150]:
val

'a,b,  guido'

In [152]:
val.find(":")

-1

In [154]:
# val.index(":")

In [155]:
val.find(",")

1

In [156]:
val.count(",")

2

In [157]:
val

'a,b,  guido'

In [158]:
val.replace(",", "::")

'a::b::  guido'

In [159]:
val.replace(",", "")

'ab  guido'

### Regular Expressions

In [160]:
import re

In [161]:
text = "foo    bar\t baz  \tqux"
text

'foo    bar\t baz  \tqux'

In [162]:
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [163]:
regex = re.compile(r"\s+")

In [164]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [165]:
regex.findall(text)

['    ', '\t ', '  \t']

In [166]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

In [167]:
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

In [170]:
# re.IGNORECASE makes the regex case insensitive
regex = re.compile(pattern, flags = re.IGNORECASE)

In [169]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [171]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [172]:
text[m.start():m.end()]

'dave@google.com'

In [173]:
print(regex.match(text))

None


In [174]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [175]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [176]:
regex = re.compile(pattern, flags = re.IGNORECASE)

In [177]:
m = regex.match("wesm@bright.net")

In [178]:
m.groups()

('wesm', 'bright', 'net')

In [179]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [180]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


### String Functions in pandas

In [181]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}
data

{'Dave': 'dave@google.com',
 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gmail.com',
 'Wes': nan}

In [182]:
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [183]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [184]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [185]:
data_as_string_ext = data.astype('string')
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [187]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [188]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
data.str.findall(pattern, flags = re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [189]:
matches = data.str.findall(pattern, flags = re.IGNORECASE).str[0]
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [190]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [191]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [192]:
data.str.extract(pattern, flags = re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

## 7.5 Categorical Data

### Background and Motivation

In [193]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [194]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [195]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [196]:
values = pd.Series([0, 1, 0, 0] * 2)
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [198]:
dim = pd.Series(['apple', 'orange'])
dim

0     apple
1    orange
dtype: object

In [199]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

### Categorical Extension Type in pandas

In [200]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
N

8

In [201]:
rng = np.random.default_rng(seed = 12345)

In [202]:
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size = N),
                   'weight': rng.uniform(0, 4, size = N)},
                  columns = ['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [203]:
fruit_cat = df["fruit"].astype("category")
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [204]:
c = fruit_cat.array
type(c)

pandas.core.arrays.categorical.Categorical

In [205]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [206]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [207]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [208]:
df["fruit"] = df["fruit"].astype("category")
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [209]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [210]:
categories = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]

In [211]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [212]:
ordered_cat = pd.Categorical.from_codes(codes, categories,
                                        ordered = True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [214]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

### Computations with Categoricals

In [215]:
rng = np.random.default_rng(seed = 12345)

In [216]:
draws = rng.standard_normal(1000)

In [217]:
draws[:5]

array([-1.4238,  1.2637, -0.8707, -0.2592, -0.0753])

In [218]:
bins = pd.qcut(draws, 4)
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [219]:
bins = pd.qcut(draws, 4, labels = ["Q1", "Q2", "Q3", "Q4"])
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [220]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [221]:
bins = pd.Series(bins, name = "quartile")

In [222]:
results = (pd.Series(draws)
           .groupby(bins)
           .agg(["count", "min", "max"])
           .reset_index())
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [223]:
results["quartile"]

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

#### Better performance with categoricals

In [224]:
N = 10_000_000

In [225]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [226]:
categories = labels.astype("category")

In [227]:
labels.memory_usage(deep = True)

600000128

In [228]:
categories.memory_usage(deep = True)

10000540

In [229]:
600000128/10000540

59.99677297425939

In [230]:
%time _ = labels.astype("category")

Wall time: 798 ms


In [231]:
%timeit labels.value_counts()

658 ms ± 21.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [232]:
%timeit categories.value_counts()

117 ms ± 3.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Categorical Methods

In [233]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)
s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: object

In [234]:
cat_s = s.astype("category")
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [235]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [236]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [237]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [238]:
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [239]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
dtype: int64

In [240]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
dtype: int64

In [241]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [242]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

#### Creating dummy variables for modeling

In [243]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [244]:
pd.get_dummies(cat_s, dtype = float)

a    b    c    d
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0
4  1.0  0.0  0.0  0.0
5  0.0  1.0  0.0  0.0
6  0.0  0.0  1.0  0.0
7  0.0  0.0  0.0  1.0