# <b>Python for Data Analysis</b>
# 4.  NumPy Basics: Arrays and Vectorized Computation

In [1]:
import numpy as np
import pandas as pd
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80
np.set_printoptions(precision=4, suppress=True)

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels as sm

In [3]:
my_arr = np.arange(1_000_000)

In [4]:
my_list = list(range(1_000_000))

In [5]:
%timeit my_arr2 = my_arr * 2

1.97 ms ± 127 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%timeit my_list2 = [x * 2 for x in my_list]

90.6 ms ± 7.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## 4.1 The NumPy ndarray: A Multidimensional Array Object

In [7]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [8]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [9]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

### Creating ndarrays

In [12]:
data1 = [6, 7.5, 8, 0, 1]

In [13]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [15]:
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr2.ndim

2

In [17]:
arr2.shape

(2, 4)

In [18]:
arr1.dtype

dtype('float64')

In [19]:
arr2.dtype

dtype('int32')

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.empty((2, 3, 2))

array([[[8.7367e-312, 2.4703e-322],
        [0.0000e+000, 0.0000e+000],
        [1.1247e-312, 1.6159e+184]],

       [[7.7344e-091, 7.2660e-043],
        [5.4509e-067, 1.4509e-047],
        [3.9991e+252, 1.9098e-312]]])

In [23]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
arrTest = np.arange(15)
arrTest.dtype

dtype('int32')

In [25]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
np.ones_like(arr2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
np.empty_like(arr2)

array([[1936289056, 1684104556,  174550633, 1948282473],
       [1702061416, 1953067808, 1769234805,  779316847]])

In [28]:
np.full_like(arr2, 6.322)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

In [29]:
np.full_like(arr2, 6.322)

array([[6, 6, 6, 6],
       [6, 6, 6, 6]])

### Data Types for ndarrays

In [30]:
arr1 = np.array([1, 2, 3], dtype = np.float64)

In [31]:
arr2 = np.array([1, 2, 3], dtype = np.int32)

In [32]:
arr1.dtype

dtype('float64')

In [33]:
arr2.dtype

dtype('int32')

In [34]:
arr = np.array([1, 2, 3, 4, 5])

In [35]:
arr.dtype

dtype('int32')

In [36]:
float_arr = arr.astype(np.float64)

In [37]:
float_arr

array([1., 2., 3., 4., 5.])

In [38]:
float_arr.dtype

dtype('float64')

In [39]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [40]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [41]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype = np.string_)

In [42]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [43]:
int_array = np.arange(10)

In [44]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype = np.float64)

In [45]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [46]:
zeros_uint32 = np.zeros(8, dtype = "u4")

In [47]:
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

### Arithmetic with NumPy Arrays

In [48]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [49]:
arr.dtype

dtype('float64')

In [50]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [51]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
1 / arr

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

In [53]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [54]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [55]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [56]:
arr2 == arr

array([[False, False, False],
       [False, False, False]])

In [57]:
arr2 != arr

array([[ True,  True,  True],
       [ True,  True,  True]])

### Basic Indexing and Slicing

In [58]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr[5]

5

In [60]:
arr[5:8]

array([5, 6, 7])

In [61]:
arr[5:8] = 12

In [62]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [64]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [65]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [67]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [68]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [69]:
arr2d[0][2]

3

In [70]:
arr2d[0, 2]

3

In [71]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
old_values = arr3d[0].copy()

In [75]:
arr3d[0] = 42

In [76]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[0] = old_values

In [79]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
arr3d[1, 0]

array([7, 8, 9])

In [82]:
arr3d[1, 0, 1]

8

In [83]:
x = arr3d[1]

In [84]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [85]:
x[0]

array([7, 8, 9])

### Indexing with slices

In [86]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [87]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [89]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [93]:
lower_dim_slice = arr2d[1, :2]
lower_dim_slice

array([4, 5])

In [98]:
lower_dim_slice.shape

(2,)

In [100]:
arr2d[:2, 2]

array([3, 6])

In [101]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [102]:
arr2d[:2, 1:] = 0

In [103]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [106]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [107]:
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [109]:
print(names.shape)
print(data.shape)

(7,)
(7, 2)


In [110]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [111]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [112]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [113]:
data[names == "Bob", 1]

array([7, 0])

In [114]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [115]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [118]:
data[names != "Bob"]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [118]:
data[names != "Bob"]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [122]:
mask = (names == "Bob") | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [123]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [125]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [126]:
maskTest = (names == "Joe") | (names == "Will")
maskTest

array([False,  True,  True, False,  True,  True,  True])

In [127]:
data[maskTest]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [128]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [129]:
data[data < 0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [130]:
data[names != "Joe"] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

### Fancy Indexing

In [131]:
arr = np.zeros((8, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [132]:
for i in range(8):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [133]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [134]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [135]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [136]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [138]:
arr[[1, 5, 7, 2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [137]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [139]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [140]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

### Transposing Arrays and Swapping Axes

In [143]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [144]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [145]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], 
                [-1, 0, -1], [1, 0, 1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [146]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [147]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [148]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [149]:
arr.swapaxes(0, 1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])

## 4.2 Pseudorandom Number Generation