# <b>Python for Data Analysis</b>
# 7.  Data Cleaning and Preparation

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels as sm
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80
np.set_printoptions(precision=4, suppress=True)
from pandas import Series, DataFrame

## 7.1 Handling Missing Data

In [2]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [3]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [5]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [6]:
float_data = pd.Series([1, 2, None], dtype = 'float64')
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [7]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

### Filtering Out Missing Data

In [8]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [9]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [13]:
data.dropna(how = "all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [14]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [15]:
data[4] = np.nan
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [16]:
data.dropna(axis = "columns", how = "all")

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [17]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df

0         1         2
0  0.811792  0.312147 -0.762631
1  0.303413 -1.819128 -1.080864
2  0.468674 -2.027686  1.965170
3  0.613158  1.540092 -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [18]:
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

0         1         2
0  0.811792       NaN       NaN
1  0.303413       NaN       NaN
2  0.468674       NaN  1.965170
3  0.613158       NaN -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [19]:
df.dropna()

0         1         2
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [20]:
df.dropna(thresh = 2)

0         1         2
2  0.468674       NaN  1.965170
3  0.613158       NaN -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

### Filling In Missing Data

In [21]:
df

0         1         2
0  0.811792       NaN       NaN
1  0.303413       NaN       NaN
2  0.468674       NaN  1.965170
3  0.613158       NaN -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [22]:
df.fillna(0)

0         1         2
0  0.811792  0.000000  0.000000
1  0.303413  0.000000  0.000000
2  0.468674  0.000000  1.965170
3  0.613158  0.000000 -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [23]:
df.fillna(df.mean())

0         1         2
0  0.811792  0.442686  0.086863
1  0.303413  0.442686  0.086863
2  0.468674  0.442686  1.965170
3  0.613158  0.442686 -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [24]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.811792  0.500000  0.000000
1  0.303413  0.500000  0.000000
2  0.468674  0.500000  1.965170
3  0.613158  0.500000 -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [25]:
col1mean = df[0].mean()
col1mean

0.3447694416065867

In [26]:
col2mean = df[1].mean()
col2mean

0.4426859700447698

In [27]:
col3mean = df[2].mean()
col3mean

0.08686303497060649

In [30]:
df.fillna({0: col1mean, 
           1: col2mean, 
           2: col3mean})

0         1         2
0  0.811792  0.442686  0.086863
1  0.303413  0.442686  0.086863
2  0.468674  0.442686  1.965170
3  0.613158  0.442686 -1.930849
4  1.347839  1.713292 -0.159170
5 -0.792129 -0.250666 -0.242933
6 -0.339361 -0.134568  0.802097

In [32]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df

0         1         2
0  0.474530 -0.393077 -0.967331
1 -0.655516 -0.444019  0.805094
2  0.197483 -0.031589 -0.919530
3 -1.436841  0.402624  0.191649
4 -0.754962  1.280132  0.120549
5 -0.261049 -0.579450  1.253678

In [34]:
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

0         1         2
0  0.474530 -0.393077 -0.967331
1 -0.655516 -0.444019  0.805094
2  0.197483       NaN -0.919530
3 -1.436841       NaN  0.191649
4 -0.754962       NaN       NaN
5 -0.261049       NaN       NaN

In [35]:
df.fillna(method = "ffill")

0         1         2
0  0.474530 -0.393077 -0.967331
1 -0.655516 -0.444019  0.805094
2  0.197483 -0.444019 -0.919530
3 -1.436841 -0.444019  0.191649
4 -0.754962 -0.444019  0.191649
5 -0.261049 -0.444019  0.191649

In [36]:
df.fillna(method = "ffill", limit = 2)

0         1         2
0  0.474530 -0.393077 -0.967331
1 -0.655516 -0.444019  0.805094
2  0.197483 -0.444019 -0.919530
3 -1.436841 -0.444019  0.191649
4 -0.754962       NaN  0.191649
5 -0.261049       NaN  0.191649

In [37]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [38]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 7.2 Data Transformation

### Removing Duplicates

In [39]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [40]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [42]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [43]:
data["v1"] = range(7)

In [44]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [45]:
data.drop_duplicates(subset = ["k1"])

k1  k2  v1
0  one   1   0
1  two   1   1

In [46]:
data.drop_duplicates(subset = ["k2"])

k1  k2  v1
0  one   1   0
2  one   2   2
3  two   3   3
5  two   4   5

In [47]:
data.drop_duplicates(["k1", "k2"], keep = "last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming Data Using a Function or Mapping

In [48]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [49]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [51]:
data["animal"] = data["food"].map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [52]:
def get_animal(x):
    return meat_to_animal[x]

In [53]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### Replacing Values

In [54]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [55]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [56]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [62]:
data.replace([data[data < 0]], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [63]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [64]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Renaming Axis Indexes

In [65]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index = ["Ohio", "Colorado", "New York"],
                    columns = ["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [66]:
def transform(x):
    return x[:4].upper()

In [68]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [74]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [75]:
data.index

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [76]:
data.index = data.index.map(transform)

In [77]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [78]:
data.rename(index = str.title, columns = str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [79]:
data.rename(index = {"OHIO": "INDIANA"},
            columns = {"three": "peekaboo"})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

### Discretization and Binning

In [80]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [81]:
bins = [18, 25, 35, 60, 100]

In [82]:
age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [83]:
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [84]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [85]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [86]:
pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [87]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [88]:
pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
dtype: int64

In [89]:
pd.cut(ages, bins, right = False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [90]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [91]:
pd.cut(ages, bins, labels = group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [92]:
data = np.random.uniform(size = 20)

In [93]:
pd.cut(data, 4, precision = 2)

[(0.77, 1.0], (0.53, 0.77], (0.069, 0.3], (0.069, 0.3], (0.069, 0.3], ..., (0.3, 0.53], (0.53, 0.77], (0.069, 0.3], (0.069, 0.3], (0.53, 0.77]]
Length: 20
Categories (4, interval[float64, right]): [(0.069, 0.3] < (0.3, 0.53] < (0.53, 0.77] < (0.77, 1.0]]

In [94]:
data = np.random.standard_normal(1000)
quartiles = pd.qcut(data, 4, precision = 2)
quartiles

[(0.71, 3.76], (0.71, 3.76], (0.71, 3.76], (-0.68, 0.014], (0.71, 3.76], ..., (-0.68, 0.014], (-0.68, 0.014], (0.71, 3.76], (-3.82, -0.68], (0.71, 3.76]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.82, -0.68] < (-0.68, 0.014] < (0.014, 0.71] < (0.71, 3.76]]

In [95]:
pd.value_counts(quartiles)

(-3.82, -0.68]    250
(-0.68, 0.014]    250
(0.014, 0.71]     250
(0.71, 3.76]      250
dtype: int64

In [96]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.8129999999999997, -1.25]    100
(-1.25, 0.0142]                 400
(0.0142, 1.284]                 400
(1.284, 3.762]                  100
dtype: int64

In [102]:
dfTest = np.arange(100)
dfTest

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [108]:
pd.cut(dfTest, [0, 15, 50, 60, 100]).value_counts()

(0, 15]      15
(15, 50]     35
(50, 60]     10
(60, 100]    39
dtype: int64

In [108]:
pd.cut(dfTest, [0, 15, 50, 60, 100]).value_counts()

(0, 15]      15
(15, 50]     35
(50, 60]     10
(60, 100]    39
dtype: int64

### Detecting and Filtering Outliers

In [109]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data

0         1         2         3
0   -1.417758  0.743890  0.675199 -0.886544
1    1.979514 -0.129467 -0.763258  0.584969
2   -0.519349  1.125507 -1.263263  0.337187
3    0.884150  0.061580 -0.696149 -1.581202
4   -0.543634 -2.056615 -0.970453 -0.057096
..        ...       ...       ...       ...
995 -0.138223 -0.230692  1.113294  1.358675
996 -0.467795 -1.124462  1.382013 -2.062655
997 -0.407402  0.355065  0.553154  0.789942
998 -0.353654  0.312514  0.215295  0.012161
999  0.316937 -0.925420  0.735794  1.409310

[1000 rows x 4 columns]

In [110]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.005209     0.013854    -0.040344     0.042829
std       1.019918     1.003715     0.963698     0.994820
min      -3.381881    -2.798622    -2.975792    -3.002567
25%      -0.679878    -0.647186    -0.715405    -0.630336
50%       0.002293     0.050315    -0.062652     0.016541
75%       0.674035     0.660457     0.629786     0.731469
max       3.872668     3.470999     2.948149     2.843463

In [111]:
data[2]

0      0.675199
1     -0.763258
2     -1.263263
3     -0.696149
4     -0.970453
         ...   
995    1.113294
996    1.382013
997    0.553154
998    0.215295
999    0.735794
Name: 2, Length: 1000, dtype: float64

In [112]:
col = data[2]

In [117]:
col[col < -2.7]

568   -2.975792
752   -2.906603
Name: 2, dtype: float64

In [117]:
col[col < -2.7]

568   -2.975792
752   -2.906603
Name: 2, dtype: float64

In [117]:
col[col < -2.7]

568   -2.975792
752   -2.906603
Name: 2, dtype: float64

In [118]:
data[(data.abs() > 3).any(axis = "columns")]

0         1         2         3
95  -0.283141  0.330015 -0.421116 -3.002567
142  3.003804 -1.110863 -1.964108  0.948988
200 -3.381881 -0.951867 -0.359264 -0.959585
467  1.054170  3.470999  0.794451 -1.047008
639  3.872668  0.602980 -1.582059 -0.951343
936 -3.004480  0.324877 -0.982725  0.831026

In [126]:
data[data.abs() > 3] = np.sign(data) * 3

In [127]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.005699     0.013383    -0.040344     0.042832
std       1.015743     1.002200     0.963698     0.994812
min      -3.000000    -2.798622    -2.975792    -3.000000
25%      -0.679878    -0.647186    -0.715405    -0.630336
50%       0.002293     0.050315    -0.062652     0.016541
75%       0.674035     0.660457     0.629786     0.731469
max       3.000000     3.000000     2.948149     2.843463

In [129]:
test1 = np.arange(10)
test1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
test1[test1 < 5] = np.sign(test1[test1 < 5]) * 10

In [134]:
test1

array([ 0, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [135]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0  1.0 -1.0
1  1.0 -1.0 -1.0  1.0
2 -1.0  1.0 -1.0  1.0
3  1.0  1.0 -1.0 -1.0
4 -1.0 -1.0 -1.0 -1.0

### Permutation and Random Sampling